#!/usr/bin/env python3
"""Generate a FINAL CURRENT SCHEMA export of the RedArt `public` schema.

Read-only catalog introspection against the currently connected database
(the PG* env vars). Emits executable, dependency-ordered SQL into
scripts/target_schema_parts/ plus a manifest.

Deliberately excluded:
  * all data, all secrets, all vault contents
  * Supabase-managed base schemas (auth, storage, realtime, vault, ...) -
    only RedArt-created policies on storage.objects are emitted
  * cron jobs, pg_net callbacks, and any production-specific schedule

Run from the repo root:  python3 scripts/build_target_schema_export.py
Nothing is executed against the target; this only writes files.
"""
from __future__ import annotations

import os
import subprocess

OUT = "scripts/target_schema_parts"
RS = "\x1e"  # record separator used to split multi-line psql values


def q(sql: str) -> list[list[str]]:
    """Run a read-only query, return rows of columns."""
    res = subprocess.run(
        ["psql", "-At", "-F", "\x1f", "-R", RS, "-c", sql],
        capture_output=True, text=True, check=True,
    )
    out = res.stdout.strip(RS + "\n")
    if not out:
        return []
    return [r.split("\x1f") for r in out.split(RS)]


HEADER = """-- =====================================================================
-- RedArt - CURRENT SCHEMA EXPORT (generated, do not edit by hand)
-- Part {n}: {title}
-- Source: live `public` schema, catalog introspection, read-only.
-- Contains no data, no secrets, no cron/net schedules.
-- Execute the parts strictly in filename order (01 -> {last}).
-- =====================================================================

"""


def write(idx: int, name: str, title: str, body: str, last: str) -> tuple[str, int]:
    path = f"{OUT}/{idx:02d}_{name}.sql"
    with open(path, "w") as fh:
        fh.write(HEADER.format(n=idx, title=title, last=last) + body.rstrip() + "\n")
    return path, os.path.getsize(path)


def enums() -> tuple[str, int]:
    rows = q("""
      select t.typname,
             string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder)
      from pg_type t
      join pg_namespace n on n.oid = t.typnamespace
      join pg_enum e on e.enumtypid = t.oid
      where n.nspname = 'public'
      group by t.typname
      order by t.typname
    """)
    out = []
    for name, labels in rows:
        out.append(f"CREATE TYPE public.{name} AS ENUM ({labels});")
    return "\n".join(out), len(rows)


def composite_domains() -> tuple[str, int]:
    rows = q("""
      select t.typname, pg_catalog.format_type(t.typbasetype, t.typtypmod),
             coalesce(t.typnotnull::text, 'f')
      from pg_type t
      join pg_namespace n on n.oid = t.typnamespace
      where n.nspname = 'public' and t.typtype = 'd'
      order by 1
    """)
    out = [f"CREATE DOMAIN public.{r[0]} AS {r[1]}"
           + (" NOT NULL" if r[2] == "t" else "") + ";" for r in rows]
    return "\n".join(out), len(rows)


def tables() -> tuple[str, int, list[str]]:
    names = [r[0] for r in q("""
      select c.relname from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public' and c.relkind = 'r'
      order by c.relname
    """)]
    out = []
    for t in names:
        cols = q(f"""
          select a.attname,
                 pg_catalog.format_type(a.atttypid, a.atttypmod),
                 coalesce(pg_get_expr(d.adbin, d.adrelid), ''),
                 a.attnotnull::text,
                 a.attidentity
          from pg_attribute a
          left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
          where a.attrelid = 'public.{t}'::regclass
            and a.attnum > 0 and not a.attisdropped
          order by a.attnum
        """)
        lines = []
        for name, typ, default, notnull, identity in cols:
            piece = f"  {name} {typ}"
            if identity == "a":
                piece += " GENERATED ALWAYS AS IDENTITY"
            elif identity == "d":
                piece += " GENERATED BY DEFAULT AS IDENTITY"
            elif default:
                piece += f" DEFAULT {default}"
            if notnull == "t":
                piece += " NOT NULL"
            lines.append(piece)
        out.append(f"CREATE TABLE public.{t} (\n" + ",\n".join(lines) + "\n);")
    return "\n\n".join(out), len(names), names


def constraints() -> tuple[str, int]:
    # p/u/c first, then f (FKs) so referenced keys already exist.
    out, total = [], 0
    for kinds, label in ((("p", "u", "c"), "primary key / unique / check"), (("f",), "foreign key")):
        rows = q(f"""
          select rel.relname, con.conname, pg_get_constraintdef(con.oid)
          from pg_constraint con
          join pg_class rel on rel.oid = con.conrelid
          join pg_namespace n on n.oid = rel.relnamespace
          where n.nspname = 'public'
            and con.contype in ({','.join("'" + k + "'" for k in kinds)})
          order by rel.relname, con.conname
        """)
        out.append(f"-- {label} ({len(rows)})")
        for table, name, definition in rows:
            out.append(f"ALTER TABLE public.{table} ADD CONSTRAINT {name} {definition};")
        out.append("")
        total += len(rows)
    return "\n".join(out), total


def indexes() -> tuple[str, int]:
    rows = q("""
      select i.indexdef
      from pg_indexes i
      where i.schemaname = 'public'
        and not exists (
          select 1 from pg_constraint c
          join pg_class rel on rel.oid = c.conrelid
          join pg_namespace n on n.oid = rel.relnamespace
          where n.nspname = 'public' and c.conname = i.indexname
        )
      order by i.tablename, i.indexname
    """)
    return "\n".join(r[0].rstrip(";") + ";" for r in rows), len(rows)


def functions() -> tuple[list[str], int]:
    rows = q("""
      select pg_get_functiondef(p.oid)
      from pg_proc p
      join pg_namespace n on n.oid = p.pronamespace
      where n.nspname = 'public' and p.prokind in ('f', 'p')
      order by p.proname, p.oid
    """)
    defs = [r[0].rstrip().rstrip(";") + ";\n" for r in rows]
    # sanity: no scheduling / outbound http inside function bodies
    bad = [d for d in defs if "net.http" in d or "cron." in d]
    if bad:
        raise SystemExit(f"refusing: {len(bad)} function(s) reference cron/net")
    return defs, len(defs)


def triggers() -> tuple[str, int]:
    rows = q("""
      select pg_get_triggerdef(t.oid)
      from pg_trigger t
      join pg_class c on c.oid = t.tgrelid
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public' and not t.tgisinternal
      order by c.relname, t.tgname
    """)
    return "\n".join(r[0].rstrip(";") + ";" for r in rows), len(rows)


def views() -> tuple[str, int]:
    rows = q("""
      select c.relname, pg_get_viewdef(c.oid, true)
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public' and c.relkind = 'v'
      order by c.relname
    """)
    out = [f"CREATE OR REPLACE VIEW public.{r[0]} AS\n{r[1].rstrip().rstrip(';')};" for r in rows]
    return "\n\n".join(out), len(rows)


def grants_and_rls(table_names: list[str]) -> tuple[str, int]:
    rows = q("""
      select table_name, grantee, string_agg(privilege_type, ', ' order by privilege_type)
      from information_schema.role_table_grants
      where table_schema = 'public'
        and grantee in ('anon', 'authenticated', 'service_role')
      group by table_name, grantee
      order by table_name, grantee
    """)
    out = ["-- GRANTs for the Data API roles"]
    for table, grantee, privs in rows:
        out.append(f"GRANT {privs} ON public.{table} TO {grantee};")
    out.append("")
    rls = q("""
      select c.relname from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity
      order by c.relname
    """)
    out.append(f"-- Row Level Security enabled on {len(rls)} of {len(table_names)} tables")
    for (t,) in [(r[0],) for r in rls]:
        out.append(f"ALTER TABLE public.{t} ENABLE ROW LEVEL SECURITY;")
    forced = q("""
      select c.relname from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public' and c.relkind = 'r' and c.relforcerowsecurity
      order by c.relname
    """)
    for r in forced:
        out.append(f"ALTER TABLE public.{r[0]} FORCE ROW LEVEL SECURITY;")
    return "\n".join(out), len(rows) + len(rls)


def policy_sql(schema: str) -> tuple[str, int]:
    rows = q(f"""
      select tablename, policyname, permissive, roles, cmd,
             coalesce(qual, ''), coalesce(with_check, '')
      from pg_policies
      where schemaname = '{schema}'
      order by tablename, policyname
    """)
    out = []
    for table, name, permissive, roles, cmd, qual, check in rows:
        role_list = roles.strip("{}").replace('"', "")
        stmt = [f'CREATE POLICY "{name}" ON {schema}.{table}']
        stmt.append(f"  AS {permissive.upper()}")
        stmt.append(f"  FOR {cmd}")
        if role_list:
            stmt.append(f"  TO {role_list}")
        if qual:
            stmt.append(f"  USING ({qual})")
        if check:
            stmt.append(f"  WITH CHECK ({check})")
        out.append("\n".join(stmt) + ";")
    return "\n\n".join(out), len(rows)


def realtime() -> tuple[str, int]:
    rows = q("""
      select tablename from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public'
      order by tablename
    """)
    out = ["-- Realtime publication membership (publication itself is Supabase-managed)"]
    for r in rows:
        out.append(f"ALTER PUBLICATION supabase_realtime ADD TABLE public.{r[0]};")
    replica = q("""
      select c.relname from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public' and c.relkind = 'r' and c.relreplident = 'f'
      order by c.relname
    """)
    if replica:
        out.append("")
        out.append("-- Tables with REPLICA IDENTITY FULL (full row payloads in realtime)")
        for r in replica:
            out.append(f"ALTER TABLE public.{r[0]} REPLICA IDENTITY FULL;")
    return "\n".join(out), len(rows)


def main() -> None:
    os.makedirs(OUT, exist_ok=True)
    for f in os.listdir(OUT):
        if f.endswith(".sql"):
            os.remove(os.path.join(OUT, f))

    enum_sql, n_enum = enums()
    dom_sql, n_dom = composite_domains()
    tbl_sql, n_tbl, tbl_names = tables()
    con_sql, n_con = constraints()
    idx_sql, n_idx = indexes()
    fn_defs, n_fn = functions()
    trg_sql, n_trg = triggers()
    view_sql, n_view = views()
    grant_sql, n_grant = grants_and_rls(tbl_names)
    pol_sql, n_pol = policy_sql("public")
    spol_sql, n_spol = policy_sql("storage")
    rt_sql, n_rt = realtime()

    half = (len(fn_defs) + 1) // 2
    fn_a, fn_b = "\n".join(fn_defs[:half]), "\n".join(fn_defs[half:])

    ext_sql = (
        "-- Extensions required by the schema. pg_cron / pg_net are intentionally\n"
        "-- OMITTED: they exist on the source only to run production schedules,\n"
        "-- which are excluded from this export.\n"
        'CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;\n'
        'CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions;\n'
    )

    last = "10"
    parts = [
        (1, "extensions_types", "extensions, enums and domains",
         ext_sql + "\n" + enum_sql + ("\n\n" + dom_sql if dom_sql else ""),
         {"extensions": 2, "enums": n_enum, "domains": n_dom}),
        (2, "tables", "tables, columns and defaults (no constraints yet)",
         tbl_sql, {"tables": n_tbl}),
        (3, "constraints", "primary keys, unique, check, then foreign keys",
         con_sql, {"constraints": n_con}),
        (4, "indexes", "non-constraint indexes", idx_sql, {"indexes": n_idx}),
        (5, "functions_part1", "functions / RPCs (1 of 2)", fn_a, {"functions": half}),
        (6, "functions_part2", "functions / RPCs (2 of 2)", fn_b, {"functions": n_fn - half}),
        (7, "triggers", "triggers on public tables", trg_sql, {"triggers": n_trg}),
        (8, "views", "views", view_sql, {"views": n_view}),
        (9, "grants_rls", "Data API grants and RLS enablement",
         grant_sql, {"grant_statements+rls": n_grant}),
        (10, "policies", "RLS policies (public, then storage.objects) and realtime",
         pol_sql + "\n\n-- ---- storage policies (RedArt-created) ----\n\n"
         + spol_sql + "\n\n" + rt_sql,
         {"public_policies": n_pol, "storage_policies": n_spol, "realtime_tables": n_rt}),
    ]

    manifest = [
        "# RedArt target schema export - manifest\n",
        "Final **current schema** export of the live `public` schema "
        "(catalog introspection, read-only). This is NOT a historical "
        "migration replay - see `scripts/redart_target_manifest.md` for that.\n",
        "Regenerate with `python3 scripts/build_target_schema_export.py`.\n",
        "## Execution order\n",
        "Run every part in strict filename order against the empty target:\n",
        "```bash",
        'for f in scripts/target_schema_parts/*.sql; do',
        '  psql "$TARGET_DB_URL" -v ON_ERROR_STOP=1 -f "$f" || break',
        "done",
        "```\n",
        "| # | File | Contents | Objects | Size |",
        "|---|------|----------|---------|------|",
    ]
    for idx, name, title, body, counts in parts:
        path, size = write(idx, name, title, body, last)
        cnt = ", ".join(f"{k}: {v}" for k, v in counts.items())
        manifest.append(f"| {idx:02d} | `{os.path.basename(path)}` | {title} | {cnt} | {size // 1024} KB |")

    manifest += [
        "\n## Excluded on purpose\n",
        "- All table data, all secrets, all vault contents.",
        "- Supabase-managed schemas (`auth`, `storage` base objects, `realtime`, `vault`, `graphql`) - "
        "only RedArt-created policies on `storage.objects` are included, in part 10.",
        "- `pg_cron` jobs and `pg_net` HTTP callbacks, and the `pg_cron`/`pg_net` extensions themselves: "
        "the mirror must never run production schedules or post to production endpoints.",
        "- Storage buckets (Supabase rejects SQL writes to `storage.buckets`); create the 15 private "
        "buckets through the Storage API/UI before running part 10.",
        "- `auth.users` rows and any auth configuration.\n",
        "## Notes\n",
        "- Parts 1-4 are pure DDL and must run before functions, because several functions "
        "reference tables and enum types.",
        "- Part 10 assumes the helper functions from parts 5-6 exist: most policies call "
        "`has_role()`, `current_user_company_id()` and friends.",
        "- Realtime publication membership is applied with `ALTER PUBLICATION supabase_realtime ADD TABLE`; "
        "the publication itself already exists on any Supabase project.",
    ]
    with open(f"{OUT}/00_MANIFEST.md", "w") as fh:
        fh.write("\n".join(manifest) + "\n")
    print("\n".join(manifest[10:]))


if __name__ == "__main__":
    main()
