/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RiderRouteImport } from './routes/rider'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RiderIndexRouteImport } from './routes/rider.index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as TrackTripIdRouteImport } from './routes/track.$tripId'
import { Route as RiderSigninRouteImport } from './routes/rider.signin'
import { Route as RiderPlacesRouteImport } from './routes/rider.places'
import { Route as RiderHistoryRouteImport } from './routes/rider.history'
import { Route as RiderFunRouteImport } from './routes/rider.fun'
import { Route as DriverEarningsRouteImport } from './routes/driver.earnings'
import { Route as AuthenticatedTripsRouteImport } from './routes/_authenticated/trips'
import { Route as AuthenticatedSchedulesRouteImport } from './routes/_authenticated/schedules'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPassengersRouteImport } from './routes/_authenticated/passengers'
import { Route as AuthenticatedNewsFeedRouteImport } from './routes/_authenticated/news-feed'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated/news'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMedicaidTripsRouteImport } from './routes/_authenticated/medicaid-trips'
import { Route as AuthenticatedMedicaidBillingRouteImport } from './routes/_authenticated/medicaid-billing'
import { Route as AuthenticatedLiveOpsRouteImport } from './routes/_authenticated/live-ops'
import { Route as AuthenticatedIncidentsRouteImport } from './routes/_authenticated/incidents'
import { Route as AuthenticatedGamesRouteImport } from './routes/_authenticated/games'
import { Route as AuthenticatedDriversRouteImport } from './routes/_authenticated/drivers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedPayrollDriverIdRouteImport } from './routes/_authenticated/payroll.$driverId'
import { Route as AuthenticatedMedicaidTripsNewRouteImport } from './routes/_authenticated/medicaid-trips.new'

const RiderRoute = RiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderIndexRoute = RiderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RiderRoute,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const TrackTripIdRoute = TrackTripIdRouteImport.update({
  id: '/track/$tripId',
  path: '/track/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderSigninRoute = RiderSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => RiderRoute,
} as any)
const RiderPlacesRoute = RiderPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => RiderRoute,
} as any)
const RiderHistoryRoute = RiderHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => RiderRoute,
} as any)
const RiderFunRoute = RiderFunRouteImport.update({
  id: '/fun',
  path: '/fun',
  getParentRoute: () => RiderRoute,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DriverRoute,
} as any)
const AuthenticatedTripsRoute = AuthenticatedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchedulesRoute = AuthenticatedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPassengersRoute = AuthenticatedPassengersRouteImport.update({
  id: '/passengers',
  path: '/passengers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsFeedRoute = AuthenticatedNewsFeedRouteImport.update({
  id: '/news-feed',
  path: '/news-feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMedicaidTripsRoute =
  AuthenticatedMedicaidTripsRouteImport.update({
    id: '/medicaid-trips',
    path: '/medicaid-trips',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMedicaidBillingRoute =
  AuthenticatedMedicaidBillingRouteImport.update({
    id: '/medicaid-billing',
    path: '/medicaid-billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLiveOpsRoute = AuthenticatedLiveOpsRouteImport.update({
  id: '/live-ops',
  path: '/live-ops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIncidentsRoute = AuthenticatedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesRoute = AuthenticatedGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriversRoute = AuthenticatedDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayrollDriverIdRoute =
  AuthenticatedPayrollDriverIdRouteImport.update({
    id: '/payroll/$driverId',
    path: '/payroll/$driverId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMedicaidTripsNewRoute =
  AuthenticatedMedicaidTripsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedMedicaidTripsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/driver': typeof DriverRouteWithChildren
  '/rider': typeof RiderRouteWithChildren
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/games': typeof AuthenticatedGamesRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/live-ops': typeof AuthenticatedLiveOpsRoute
  '/medicaid-billing': typeof AuthenticatedMedicaidBillingRoute
  '/medicaid-trips': typeof AuthenticatedMedicaidTripsRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/news': typeof AuthenticatedNewsRoute
  '/news-feed': typeof AuthenticatedNewsFeedRoute
  '/passengers': typeof AuthenticatedPassengersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/rider/fun': typeof RiderFunRoute
  '/rider/history': typeof RiderHistoryRoute
  '/rider/places': typeof RiderPlacesRoute
  '/rider/signin': typeof RiderSigninRoute
  '/track/$tripId': typeof TrackTripIdRoute
  '/driver/': typeof DriverIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/medicaid-trips/new': typeof AuthenticatedMedicaidTripsNewRoute
  '/payroll/$driverId': typeof AuthenticatedPayrollDriverIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/games': typeof AuthenticatedGamesRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/live-ops': typeof AuthenticatedLiveOpsRoute
  '/medicaid-billing': typeof AuthenticatedMedicaidBillingRoute
  '/medicaid-trips': typeof AuthenticatedMedicaidTripsRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/news': typeof AuthenticatedNewsRoute
  '/news-feed': typeof AuthenticatedNewsFeedRoute
  '/passengers': typeof AuthenticatedPassengersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/rider/fun': typeof RiderFunRoute
  '/rider/history': typeof RiderHistoryRoute
  '/rider/places': typeof RiderPlacesRoute
  '/rider/signin': typeof RiderSigninRoute
  '/track/$tripId': typeof TrackTripIdRoute
  '/driver': typeof DriverIndexRoute
  '/rider': typeof RiderIndexRoute
  '/medicaid-trips/new': typeof AuthenticatedMedicaidTripsNewRoute
  '/payroll/$driverId': typeof AuthenticatedPayrollDriverIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/driver': typeof DriverRouteWithChildren
  '/rider': typeof RiderRouteWithChildren
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/drivers': typeof AuthenticatedDriversRoute
  '/_authenticated/games': typeof AuthenticatedGamesRoute
  '/_authenticated/incidents': typeof AuthenticatedIncidentsRoute
  '/_authenticated/live-ops': typeof AuthenticatedLiveOpsRoute
  '/_authenticated/medicaid-billing': typeof AuthenticatedMedicaidBillingRoute
  '/_authenticated/medicaid-trips': typeof AuthenticatedMedicaidTripsRouteWithChildren
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/news': typeof AuthenticatedNewsRoute
  '/_authenticated/news-feed': typeof AuthenticatedNewsFeedRoute
  '/_authenticated/passengers': typeof AuthenticatedPassengersRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/schedules': typeof AuthenticatedSchedulesRoute
  '/_authenticated/trips': typeof AuthenticatedTripsRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/rider/fun': typeof RiderFunRoute
  '/rider/history': typeof RiderHistoryRoute
  '/rider/places': typeof RiderPlacesRoute
  '/rider/signin': typeof RiderSigninRoute
  '/track/$tripId': typeof TrackTripIdRoute
  '/driver/': typeof DriverIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/_authenticated/medicaid-trips/new': typeof AuthenticatedMedicaidTripsNewRoute
  '/_authenticated/payroll/$driverId': typeof AuthenticatedPayrollDriverIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/driver'
    | '/rider'
    | '/billing'
    | '/dashboard'
    | '/drivers'
    | '/games'
    | '/incidents'
    | '/live-ops'
    | '/medicaid-billing'
    | '/medicaid-trips'
    | '/messages'
    | '/news'
    | '/news-feed'
    | '/passengers'
    | '/reports'
    | '/schedules'
    | '/trips'
    | '/driver/earnings'
    | '/rider/fun'
    | '/rider/history'
    | '/rider/places'
    | '/rider/signin'
    | '/track/$tripId'
    | '/driver/'
    | '/rider/'
    | '/medicaid-trips/new'
    | '/payroll/$driverId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/billing'
    | '/dashboard'
    | '/drivers'
    | '/games'
    | '/incidents'
    | '/live-ops'
    | '/medicaid-billing'
    | '/medicaid-trips'
    | '/messages'
    | '/news'
    | '/news-feed'
    | '/passengers'
    | '/reports'
    | '/schedules'
    | '/trips'
    | '/driver/earnings'
    | '/rider/fun'
    | '/rider/history'
    | '/rider/places'
    | '/rider/signin'
    | '/track/$tripId'
    | '/driver'
    | '/rider'
    | '/medicaid-trips/new'
    | '/payroll/$driverId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/driver'
    | '/rider'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/drivers'
    | '/_authenticated/games'
    | '/_authenticated/incidents'
    | '/_authenticated/live-ops'
    | '/_authenticated/medicaid-billing'
    | '/_authenticated/medicaid-trips'
    | '/_authenticated/messages'
    | '/_authenticated/news'
    | '/_authenticated/news-feed'
    | '/_authenticated/passengers'
    | '/_authenticated/reports'
    | '/_authenticated/schedules'
    | '/_authenticated/trips'
    | '/driver/earnings'
    | '/rider/fun'
    | '/rider/history'
    | '/rider/places'
    | '/rider/signin'
    | '/track/$tripId'
    | '/driver/'
    | '/rider/'
    | '/_authenticated/medicaid-trips/new'
    | '/_authenticated/payroll/$driverId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DriverRoute: typeof DriverRouteWithChildren
  RiderRoute: typeof RiderRouteWithChildren
  TrackTripIdRoute: typeof TrackTripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rider': {
      id: '/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/': {
      id: '/rider/'
      path: '/'
      fullPath: '/rider/'
      preLoaderRoute: typeof RiderIndexRouteImport
      parentRoute: typeof RiderRoute
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/track/$tripId': {
      id: '/track/$tripId'
      path: '/track/$tripId'
      fullPath: '/track/$tripId'
      preLoaderRoute: typeof TrackTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/signin': {
      id: '/rider/signin'
      path: '/signin'
      fullPath: '/rider/signin'
      preLoaderRoute: typeof RiderSigninRouteImport
      parentRoute: typeof RiderRoute
    }
    '/rider/places': {
      id: '/rider/places'
      path: '/places'
      fullPath: '/rider/places'
      preLoaderRoute: typeof RiderPlacesRouteImport
      parentRoute: typeof RiderRoute
    }
    '/rider/history': {
      id: '/rider/history'
      path: '/history'
      fullPath: '/rider/history'
      preLoaderRoute: typeof RiderHistoryRouteImport
      parentRoute: typeof RiderRoute
    }
    '/rider/fun': {
      id: '/rider/fun'
      path: '/fun'
      fullPath: '/rider/fun'
      preLoaderRoute: typeof RiderFunRouteImport
      parentRoute: typeof RiderRoute
    }
    '/driver/earnings': {
      id: '/driver/earnings'
      path: '/earnings'
      fullPath: '/driver/earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/_authenticated/trips': {
      id: '/_authenticated/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthenticatedTripsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedules': {
      id: '/_authenticated/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthenticatedSchedulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passengers': {
      id: '/_authenticated/passengers'
      path: '/passengers'
      fullPath: '/passengers'
      preLoaderRoute: typeof AuthenticatedPassengersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news-feed': {
      id: '/_authenticated/news-feed'
      path: '/news-feed'
      fullPath: '/news-feed'
      preLoaderRoute: typeof AuthenticatedNewsFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medicaid-trips': {
      id: '/_authenticated/medicaid-trips'
      path: '/medicaid-trips'
      fullPath: '/medicaid-trips'
      preLoaderRoute: typeof AuthenticatedMedicaidTripsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medicaid-billing': {
      id: '/_authenticated/medicaid-billing'
      path: '/medicaid-billing'
      fullPath: '/medicaid-billing'
      preLoaderRoute: typeof AuthenticatedMedicaidBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-ops': {
      id: '/_authenticated/live-ops'
      path: '/live-ops'
      fullPath: '/live-ops'
      preLoaderRoute: typeof AuthenticatedLiveOpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidents': {
      id: '/_authenticated/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthenticatedIncidentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games': {
      id: '/_authenticated/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AuthenticatedGamesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drivers': {
      id: '/_authenticated/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AuthenticatedDriversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll/$driverId': {
      id: '/_authenticated/payroll/$driverId'
      path: '/payroll/$driverId'
      fullPath: '/payroll/$driverId'
      preLoaderRoute: typeof AuthenticatedPayrollDriverIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medicaid-trips/new': {
      id: '/_authenticated/medicaid-trips/new'
      path: '/new'
      fullPath: '/medicaid-trips/new'
      preLoaderRoute: typeof AuthenticatedMedicaidTripsNewRouteImport
      parentRoute: typeof AuthenticatedMedicaidTripsRoute
    }
  }
}

interface AuthenticatedMedicaidTripsRouteChildren {
  AuthenticatedMedicaidTripsNewRoute: typeof AuthenticatedMedicaidTripsNewRoute
}

const AuthenticatedMedicaidTripsRouteChildren: AuthenticatedMedicaidTripsRouteChildren =
  {
    AuthenticatedMedicaidTripsNewRoute: AuthenticatedMedicaidTripsNewRoute,
  }

const AuthenticatedMedicaidTripsRouteWithChildren =
  AuthenticatedMedicaidTripsRoute._addFileChildren(
    AuthenticatedMedicaidTripsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDriversRoute: typeof AuthenticatedDriversRoute
  AuthenticatedGamesRoute: typeof AuthenticatedGamesRoute
  AuthenticatedIncidentsRoute: typeof AuthenticatedIncidentsRoute
  AuthenticatedLiveOpsRoute: typeof AuthenticatedLiveOpsRoute
  AuthenticatedMedicaidBillingRoute: typeof AuthenticatedMedicaidBillingRoute
  AuthenticatedMedicaidTripsRoute: typeof AuthenticatedMedicaidTripsRouteWithChildren
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRoute
  AuthenticatedNewsFeedRoute: typeof AuthenticatedNewsFeedRoute
  AuthenticatedPassengersRoute: typeof AuthenticatedPassengersRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSchedulesRoute: typeof AuthenticatedSchedulesRoute
  AuthenticatedTripsRoute: typeof AuthenticatedTripsRoute
  AuthenticatedPayrollDriverIdRoute: typeof AuthenticatedPayrollDriverIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDriversRoute: AuthenticatedDriversRoute,
  AuthenticatedGamesRoute: AuthenticatedGamesRoute,
  AuthenticatedIncidentsRoute: AuthenticatedIncidentsRoute,
  AuthenticatedLiveOpsRoute: AuthenticatedLiveOpsRoute,
  AuthenticatedMedicaidBillingRoute: AuthenticatedMedicaidBillingRoute,
  AuthenticatedMedicaidTripsRoute: AuthenticatedMedicaidTripsRouteWithChildren,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNewsRoute: AuthenticatedNewsRoute,
  AuthenticatedNewsFeedRoute: AuthenticatedNewsFeedRoute,
  AuthenticatedPassengersRoute: AuthenticatedPassengersRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSchedulesRoute: AuthenticatedSchedulesRoute,
  AuthenticatedTripsRoute: AuthenticatedTripsRoute,
  AuthenticatedPayrollDriverIdRoute: AuthenticatedPayrollDriverIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DriverRouteChildren {
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverEarningsRoute: DriverEarningsRoute,
  DriverIndexRoute: DriverIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface RiderRouteChildren {
  RiderFunRoute: typeof RiderFunRoute
  RiderHistoryRoute: typeof RiderHistoryRoute
  RiderPlacesRoute: typeof RiderPlacesRoute
  RiderSigninRoute: typeof RiderSigninRoute
  RiderIndexRoute: typeof RiderIndexRoute
}

const RiderRouteChildren: RiderRouteChildren = {
  RiderFunRoute: RiderFunRoute,
  RiderHistoryRoute: RiderHistoryRoute,
  RiderPlacesRoute: RiderPlacesRoute,
  RiderSigninRoute: RiderSigninRoute,
  RiderIndexRoute: RiderIndexRoute,
}

const RiderRouteWithChildren = RiderRoute._addFileChildren(RiderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DriverRoute: DriverRouteWithChildren,
  RiderRoute: RiderRouteWithChildren,
  TrackTripIdRoute: TrackTripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
