/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompanySlugRouteRouteImport } from './routes/$companySlug/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/owner/index'
import { Route as CompanySlugIndexRouteImport } from './routes/$companySlug/index'
import { Route as TrackTripIdRouteImport } from './routes/track.$tripId'
import { Route as RideRequestIdRouteImport } from './routes/ride.$requestId'
import { Route as OwnerSigninRouteImport } from './routes/owner/signin'
import { Route as DriverSigninRouteImport } from './routes/driver.signin'
import { Route as DispatchSigninRouteImport } from './routes/dispatch.signin'
import { Route as CompanySlugPassengerRouteImport } from './routes/$companySlug/passenger'
import { Route as CompanySlugLoginRouteImport } from './routes/$companySlug/login'
import { Route as CompanySlugDriverRouteImport } from './routes/$companySlug/driver'
import { Route as CompanySlugDispatchRouteImport } from './routes/$companySlug/dispatch'
import { Route as CompanySlugBillingRouteImport } from './routes/$companySlug/billing'
import { Route as CompanySlugSplatRouteImport } from './routes/$companySlug/$'
import { Route as CompanySlugAuthenticatedRouteRouteImport } from './routes/$companySlug/_authenticated/route'
import { Route as CompanySlugPassengerIndexRouteImport } from './routes/$companySlug/passenger.index'
import { Route as CompanySlugDriverIndexRouteImport } from './routes/$companySlug/driver.index'
import { Route as CompanySlugDispatchIndexRouteImport } from './routes/$companySlug/dispatch.index'
import { Route as CompanySlugBillingIndexRouteImport } from './routes/$companySlug/billing.index'
import { Route as ApiPublicSmsInboundRouteImport } from './routes/api/public/sms-inbound'
import { Route as ApiPublicGetTripPdfRouteImport } from './routes/api/public/get-trip-pdf'
import { Route as ApiPublicGetPortalCredentialRouteImport } from './routes/api/public/get-portal-credential'
import { Route as ApiPublicGetBillingRateRouteImport } from './routes/api/public/get-billing-rate'
import { Route as ApiPublicDiagBillingRouteImport } from './routes/api/public/diag-billing'
import { Route as CompanySlugPassengerTrackRouteImport } from './routes/$companySlug/passenger.track'
import { Route as CompanySlugPassengerSignupRouteImport } from './routes/$companySlug/passenger.signup'
import { Route as CompanySlugPassengerSafetyRouteImport } from './routes/$companySlug/passenger.safety'
import { Route as CompanySlugPassengerRewardsRouteImport } from './routes/$companySlug/passenger.rewards'
import { Route as CompanySlugPassengerProfileRouteImport } from './routes/$companySlug/passenger.profile'
import { Route as CompanySlugPassengerNewsRouteImport } from './routes/$companySlug/passenger.news'
import { Route as CompanySlugPassengerGamesRouteImport } from './routes/$companySlug/passenger.games'
import { Route as CompanySlugPassengerEventsRouteImport } from './routes/$companySlug/passenger.events'
import { Route as CompanySlugPassengerApplyRouteImport } from './routes/$companySlug/passenger.apply'
import { Route as CompanySlugDriverSigninRouteImport } from './routes/$companySlug/driver.signin'
import { Route as CompanySlugDriverProfileRouteImport } from './routes/$companySlug/driver.profile'
import { Route as CompanySlugDriverMessagesRouteImport } from './routes/$companySlug/driver.messages'
import { Route as CompanySlugDriverHistoryRouteImport } from './routes/$companySlug/driver.history'
import { Route as CompanySlugDriverExpensesRouteImport } from './routes/$companySlug/driver.expenses'
import { Route as CompanySlugDriverEarningsRouteImport } from './routes/$companySlug/driver.earnings'
import { Route as CompanySlugDispatchSigninRouteImport } from './routes/$companySlug/dispatch.signin'
import { Route as CompanySlugDispatchScheduleRouteImport } from './routes/$companySlug/dispatch.schedule'
import { Route as CompanySlugDispatchRoutesRouteImport } from './routes/$companySlug/dispatch.routes'
import { Route as CompanySlugDispatchHistoryRouteImport } from './routes/$companySlug/dispatch.history'
import { Route as CompanySlugBillingSigninRouteImport } from './routes/$companySlug/billing.signin'
import { Route as CompanySlugBillingSettingsRouteImport } from './routes/$companySlug/billing.settings'
import { Route as CompanySlugBillingChatRouteImport } from './routes/$companySlug/billing.chat'
import { Route as CompanySlugAuthenticatedTripsRouteImport } from './routes/$companySlug/_authenticated/trips'
import { Route as CompanySlugAuthenticatedTeamRouteImport } from './routes/$companySlug/_authenticated/team'
import { Route as CompanySlugAuthenticatedSchedulesRouteImport } from './routes/$companySlug/_authenticated/schedules'
import { Route as CompanySlugAuthenticatedRewardsSettingsRouteImport } from './routes/$companySlug/_authenticated/rewards-settings'
import { Route as CompanySlugAuthenticatedReportsRouteImport } from './routes/$companySlug/_authenticated/reports'
import { Route as CompanySlugAuthenticatedPlannerRouteImport } from './routes/$companySlug/_authenticated/planner'
import { Route as CompanySlugAuthenticatedPassengersRouteImport } from './routes/$companySlug/_authenticated/passengers'
import { Route as CompanySlugAuthenticatedNewsFeedRouteImport } from './routes/$companySlug/_authenticated/news-feed'
import { Route as CompanySlugAuthenticatedNewsRouteImport } from './routes/$companySlug/_authenticated/news'
import { Route as CompanySlugAuthenticatedMessagesRouteImport } from './routes/$companySlug/_authenticated/messages'
import { Route as CompanySlugAuthenticatedMedicaidTripsRouteImport } from './routes/$companySlug/_authenticated/medicaid-trips'
import { Route as CompanySlugAuthenticatedMedicaidBillingRouteImport } from './routes/$companySlug/_authenticated/medicaid-billing'
import { Route as CompanySlugAuthenticatedLiveOpsRouteImport } from './routes/$companySlug/_authenticated/live-ops'
import { Route as CompanySlugAuthenticatedIncidentsRouteImport } from './routes/$companySlug/_authenticated/incidents'
import { Route as CompanySlugAuthenticatedGamesRouteImport } from './routes/$companySlug/_authenticated/games'
import { Route as CompanySlugAuthenticatedEventsRouteImport } from './routes/$companySlug/_authenticated/events'
import { Route as CompanySlugAuthenticatedDriversRouteImport } from './routes/$companySlug/_authenticated/drivers'
import { Route as CompanySlugAuthenticatedDashboardRouteImport } from './routes/$companySlug/_authenticated/dashboard'
import { Route as CompanySlugDispatchRoutesIndexRouteImport } from './routes/$companySlug/dispatch.routes.index'
import { Route as CompanySlugAuthenticatedPayrollIndexRouteImport } from './routes/$companySlug/_authenticated/payroll.index'
import { Route as CompanySlugPassengerBookVehicleRouteImport } from './routes/$companySlug/passenger.book.vehicle'
import { Route as CompanySlugPassengerBookPickupRouteImport } from './routes/$companySlug/passenger.book.pickup'
import { Route as CompanySlugDriverTripNewRouteImport } from './routes/$companySlug/driver.trip.new'
import { Route as CompanySlugDispatchRoutesRouteIdRouteImport } from './routes/$companySlug/dispatch.routes.$routeId'
import { Route as CompanySlugAuthenticatedPayrollDriverIdRouteImport } from './routes/$companySlug/_authenticated/payroll.$driverId'
import { Route as CompanySlugAuthenticatedMedicaidTripsNewRouteImport } from './routes/$companySlug/_authenticated/medicaid-trips.new'
import { Route as CompanySlugAuthenticatedTripsTripIdProofRouteImport } from './routes/$companySlug/_authenticated/trips_.$tripId.proof'

const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugRouteRoute = CompanySlugRouteRouteImport.update({
  id: '/$companySlug',
  path: '/$companySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugIndexRoute = CompanySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanySlugRouteRoute,
} as any)
const TrackTripIdRoute = TrackTripIdRouteImport.update({
  id: '/track/$tripId',
  path: '/track/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const RideRequestIdRoute = RideRequestIdRouteImport.update({
  id: '/ride/$requestId',
  path: '/ride/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSigninRoute = OwnerSigninRouteImport.update({
  id: '/owner/signin',
  path: '/owner/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverSigninRoute = DriverSigninRouteImport.update({
  id: '/driver/signin',
  path: '/driver/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchSigninRoute = DispatchSigninRouteImport.update({
  id: '/dispatch/signin',
  path: '/dispatch/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugPassengerRoute = CompanySlugPassengerRouteImport.update({
  id: '/passenger',
  path: '/passenger',
  getParentRoute: () => CompanySlugRouteRoute,
} as any)
const CompanySlugLoginRoute = CompanySlugLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CompanySlugRouteRoute,
} as any)
const CompanySlugDriverRoute = CompanySlugDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => CompanySlugRouteRoute,
} as any)
const CompanySlugDispatchRoute = CompanySlugDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => CompanySlugRouteRoute,
} as any)
const CompanySlugBillingRoute = CompanySlugBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => CompanySlugRouteRoute,
} as any)
const CompanySlugSplatRoute = CompanySlugSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => CompanySlugRouteRoute,
} as any)
const CompanySlugAuthenticatedRouteRoute =
  CompanySlugAuthenticatedRouteRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => CompanySlugRouteRoute,
  } as any)
const CompanySlugPassengerIndexRoute =
  CompanySlugPassengerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompanySlugPassengerRoute,
  } as any)
const CompanySlugDriverIndexRoute = CompanySlugDriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanySlugDriverRoute,
} as any)
const CompanySlugDispatchIndexRoute =
  CompanySlugDispatchIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompanySlugDispatchRoute,
  } as any)
const CompanySlugBillingIndexRoute = CompanySlugBillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanySlugBillingRoute,
} as any)
const ApiPublicSmsInboundRoute = ApiPublicSmsInboundRouteImport.update({
  id: '/api/public/sms-inbound',
  path: '/api/public/sms-inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGetTripPdfRoute = ApiPublicGetTripPdfRouteImport.update({
  id: '/api/public/get-trip-pdf',
  path: '/api/public/get-trip-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGetPortalCredentialRoute =
  ApiPublicGetPortalCredentialRouteImport.update({
    id: '/api/public/get-portal-credential',
    path: '/api/public/get-portal-credential',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGetBillingRateRoute = ApiPublicGetBillingRateRouteImport.update({
  id: '/api/public/get-billing-rate',
  path: '/api/public/get-billing-rate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiagBillingRoute = ApiPublicDiagBillingRouteImport.update({
  id: '/api/public/diag-billing',
  path: '/api/public/diag-billing',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugPassengerTrackRoute =
  CompanySlugPassengerTrackRouteImport.update({
    id: '/track',
    path: '/track',
    getParentRoute: () => CompanySlugPassengerRoute,
  } as any)
const CompanySlugPassengerSignupRoute =
  CompanySlugPassengerSignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => CompanySlugPassengerRoute,
  } as any)
const CompanySlugPassengerSafetyRoute =
  CompanySlugPassengerSafetyRouteImport.update({
    id: '/safety',
    path: '/safety',
    getParentRoute: () => CompanySlugPassengerRoute,
  } as any)
const CompanySlugPassengerRewardsRoute =
  CompanySlugPassengerRewardsRouteImport.update({
    id: '/rewards',
    path: '/rewards',
    getParentRoute: () => CompanySlugPassengerRoute,
  } as any)
const CompanySlugPassengerProfileRoute =
  CompanySlugPassengerProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => CompanySlugPassengerRoute,
  } as any)
const CompanySlugPassengerNewsRoute =
  CompanySlugPassengerNewsRouteImport.update({
    id: '/news',
    path: '/news',
    getParentRoute: () => CompanySlugPassengerRoute,
  } as any)
const CompanySlugPassengerGamesRoute =
  CompanySlugPassengerGamesRouteImport.update({
    id: '/games',
    path: '/games',
    getParentRoute: () => CompanySlugPassengerRoute,
  } as any)
const CompanySlugPassengerEventsRoute =
  CompanySlugPassengerEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => CompanySlugPassengerRoute,
  } as any)
const CompanySlugPassengerApplyRoute =
  CompanySlugPassengerApplyRouteImport.update({
    id: '/apply',
    path: '/apply',
    getParentRoute: () => CompanySlugPassengerRoute,
  } as any)
const CompanySlugDriverSigninRoute = CompanySlugDriverSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => CompanySlugDriverRoute,
} as any)
const CompanySlugDriverProfileRoute =
  CompanySlugDriverProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => CompanySlugDriverRoute,
  } as any)
const CompanySlugDriverMessagesRoute =
  CompanySlugDriverMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => CompanySlugDriverRoute,
  } as any)
const CompanySlugDriverHistoryRoute =
  CompanySlugDriverHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => CompanySlugDriverRoute,
  } as any)
const CompanySlugDriverExpensesRoute =
  CompanySlugDriverExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => CompanySlugDriverRoute,
  } as any)
const CompanySlugDriverEarningsRoute =
  CompanySlugDriverEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => CompanySlugDriverRoute,
  } as any)
const CompanySlugDispatchSigninRoute =
  CompanySlugDispatchSigninRouteImport.update({
    id: '/signin',
    path: '/signin',
    getParentRoute: () => CompanySlugDispatchRoute,
  } as any)
const CompanySlugDispatchScheduleRoute =
  CompanySlugDispatchScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => CompanySlugDispatchRoute,
  } as any)
const CompanySlugDispatchRoutesRoute =
  CompanySlugDispatchRoutesRouteImport.update({
    id: '/routes',
    path: '/routes',
    getParentRoute: () => CompanySlugDispatchRoute,
  } as any)
const CompanySlugDispatchHistoryRoute =
  CompanySlugDispatchHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => CompanySlugDispatchRoute,
  } as any)
const CompanySlugBillingSigninRoute =
  CompanySlugBillingSigninRouteImport.update({
    id: '/signin',
    path: '/signin',
    getParentRoute: () => CompanySlugBillingRoute,
  } as any)
const CompanySlugBillingSettingsRoute =
  CompanySlugBillingSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => CompanySlugBillingRoute,
  } as any)
const CompanySlugBillingChatRoute = CompanySlugBillingChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => CompanySlugBillingRoute,
} as any)
const CompanySlugAuthenticatedTripsRoute =
  CompanySlugAuthenticatedTripsRouteImport.update({
    id: '/trips',
    path: '/trips',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)
const CompanySlugAuthenticatedTeamRoute =
  CompanySlugAuthenticatedTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)
const CompanySlugAuthenticatedSchedulesRoute =
  CompanySlugAuthenticatedSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)
const CompanySlugAuthenticatedRewardsSettingsRoute =
  CompanySlugAuthenticatedRewardsSettingsRouteImport.update({
    id: '/rewards-settings',
    path: '/rewards-settings',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)
const CompanySlugAuthenticatedReportsRoute =
  CompanySlugAuthenticatedReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)
const CompanySlugAuthenticatedPlannerRoute =
  CompanySlugAuthenticatedPlannerRouteImport.update({
    id: '/planner',
    path: '/planner',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)
const CompanySlugAuthenticatedPassengersRoute =
  CompanySlugAuthenticatedPassengersRouteImport.update({
    id: '/passengers',
    path: '/passengers',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)
const CompanySlugAuthenticatedNewsFeedRoute =
  CompanySlugAuthenticatedNewsFeedRouteImport.update({
    id: '/news-feed',
    path: '/news-feed',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)
const CompanySlugAuthenticatedNewsRoute =
  CompanySlugAuthenticatedNewsRouteImport.update({
    id: '/news',
    path: '/news',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)
const CompanySlugAuthenticatedMessagesRoute =
  CompanySlugAuthenticatedMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)
const CompanySlugAuthenticatedMedicaidTripsRoute =
  CompanySlugAuthenticatedMedicaidTripsRouteImport.update({
    id: '/medicaid-trips',
    path: '/medicaid-trips',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)
const CompanySlugAuthenticatedMedicaidBillingRoute =
  CompanySlugAuthenticatedMedicaidBillingRouteImport.update({
    id: '/medicaid-billing',
    path: '/medicaid-billing',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)
const CompanySlugAuthenticatedLiveOpsRoute =
  CompanySlugAuthenticatedLiveOpsRouteImport.update({
    id: '/live-ops',
    path: '/live-ops',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)
const CompanySlugAuthenticatedIncidentsRoute =
  CompanySlugAuthenticatedIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)
const CompanySlugAuthenticatedGamesRoute =
  CompanySlugAuthenticatedGamesRouteImport.update({
    id: '/games',
    path: '/games',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)
const CompanySlugAuthenticatedEventsRoute =
  CompanySlugAuthenticatedEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)
const CompanySlugAuthenticatedDriversRoute =
  CompanySlugAuthenticatedDriversRouteImport.update({
    id: '/drivers',
    path: '/drivers',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)
const CompanySlugAuthenticatedDashboardRoute =
  CompanySlugAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)
const CompanySlugDispatchRoutesIndexRoute =
  CompanySlugDispatchRoutesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompanySlugDispatchRoutesRoute,
  } as any)
const CompanySlugAuthenticatedPayrollIndexRoute =
  CompanySlugAuthenticatedPayrollIndexRouteImport.update({
    id: '/payroll/',
    path: '/payroll/',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)
const CompanySlugPassengerBookVehicleRoute =
  CompanySlugPassengerBookVehicleRouteImport.update({
    id: '/book/vehicle',
    path: '/book/vehicle',
    getParentRoute: () => CompanySlugPassengerRoute,
  } as any)
const CompanySlugPassengerBookPickupRoute =
  CompanySlugPassengerBookPickupRouteImport.update({
    id: '/book/pickup',
    path: '/book/pickup',
    getParentRoute: () => CompanySlugPassengerRoute,
  } as any)
const CompanySlugDriverTripNewRoute =
  CompanySlugDriverTripNewRouteImport.update({
    id: '/trip/new',
    path: '/trip/new',
    getParentRoute: () => CompanySlugDriverRoute,
  } as any)
const CompanySlugDispatchRoutesRouteIdRoute =
  CompanySlugDispatchRoutesRouteIdRouteImport.update({
    id: '/$routeId',
    path: '/$routeId',
    getParentRoute: () => CompanySlugDispatchRoutesRoute,
  } as any)
const CompanySlugAuthenticatedPayrollDriverIdRoute =
  CompanySlugAuthenticatedPayrollDriverIdRouteImport.update({
    id: '/payroll/$driverId',
    path: '/payroll/$driverId',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)
const CompanySlugAuthenticatedMedicaidTripsNewRoute =
  CompanySlugAuthenticatedMedicaidTripsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => CompanySlugAuthenticatedMedicaidTripsRoute,
  } as any)
const CompanySlugAuthenticatedTripsTripIdProofRoute =
  CompanySlugAuthenticatedTripsTripIdProofRouteImport.update({
    id: '/trips_/$tripId/proof',
    path: '/trips/$tripId/proof',
    getParentRoute: () => CompanySlugAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$companySlug': typeof CompanySlugRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/showcase': typeof ShowcaseRoute
  '/$companySlug/$': typeof CompanySlugSplatRoute
  '/$companySlug/billing': typeof CompanySlugBillingRouteWithChildren
  '/$companySlug/dispatch': typeof CompanySlugDispatchRouteWithChildren
  '/$companySlug/driver': typeof CompanySlugDriverRouteWithChildren
  '/$companySlug/login': typeof CompanySlugLoginRoute
  '/$companySlug/passenger': typeof CompanySlugPassengerRouteWithChildren
  '/dispatch/signin': typeof DispatchSigninRoute
  '/driver/signin': typeof DriverSigninRoute
  '/owner/signin': typeof OwnerSigninRoute
  '/ride/$requestId': typeof RideRequestIdRoute
  '/track/$tripId': typeof TrackTripIdRoute
  '/$companySlug/': typeof CompanySlugIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/$companySlug/dashboard': typeof CompanySlugAuthenticatedDashboardRoute
  '/$companySlug/drivers': typeof CompanySlugAuthenticatedDriversRoute
  '/$companySlug/events': typeof CompanySlugAuthenticatedEventsRoute
  '/$companySlug/games': typeof CompanySlugAuthenticatedGamesRoute
  '/$companySlug/incidents': typeof CompanySlugAuthenticatedIncidentsRoute
  '/$companySlug/live-ops': typeof CompanySlugAuthenticatedLiveOpsRoute
  '/$companySlug/medicaid-billing': typeof CompanySlugAuthenticatedMedicaidBillingRoute
  '/$companySlug/medicaid-trips': typeof CompanySlugAuthenticatedMedicaidTripsRouteWithChildren
  '/$companySlug/messages': typeof CompanySlugAuthenticatedMessagesRoute
  '/$companySlug/news': typeof CompanySlugAuthenticatedNewsRoute
  '/$companySlug/news-feed': typeof CompanySlugAuthenticatedNewsFeedRoute
  '/$companySlug/passengers': typeof CompanySlugAuthenticatedPassengersRoute
  '/$companySlug/planner': typeof CompanySlugAuthenticatedPlannerRoute
  '/$companySlug/reports': typeof CompanySlugAuthenticatedReportsRoute
  '/$companySlug/rewards-settings': typeof CompanySlugAuthenticatedRewardsSettingsRoute
  '/$companySlug/schedules': typeof CompanySlugAuthenticatedSchedulesRoute
  '/$companySlug/team': typeof CompanySlugAuthenticatedTeamRoute
  '/$companySlug/trips': typeof CompanySlugAuthenticatedTripsRoute
  '/$companySlug/billing/chat': typeof CompanySlugBillingChatRoute
  '/$companySlug/billing/settings': typeof CompanySlugBillingSettingsRoute
  '/$companySlug/billing/signin': typeof CompanySlugBillingSigninRoute
  '/$companySlug/dispatch/history': typeof CompanySlugDispatchHistoryRoute
  '/$companySlug/dispatch/routes': typeof CompanySlugDispatchRoutesRouteWithChildren
  '/$companySlug/dispatch/schedule': typeof CompanySlugDispatchScheduleRoute
  '/$companySlug/dispatch/signin': typeof CompanySlugDispatchSigninRoute
  '/$companySlug/driver/earnings': typeof CompanySlugDriverEarningsRoute
  '/$companySlug/driver/expenses': typeof CompanySlugDriverExpensesRoute
  '/$companySlug/driver/history': typeof CompanySlugDriverHistoryRoute
  '/$companySlug/driver/messages': typeof CompanySlugDriverMessagesRoute
  '/$companySlug/driver/profile': typeof CompanySlugDriverProfileRoute
  '/$companySlug/driver/signin': typeof CompanySlugDriverSigninRoute
  '/$companySlug/passenger/apply': typeof CompanySlugPassengerApplyRoute
  '/$companySlug/passenger/events': typeof CompanySlugPassengerEventsRoute
  '/$companySlug/passenger/games': typeof CompanySlugPassengerGamesRoute
  '/$companySlug/passenger/news': typeof CompanySlugPassengerNewsRoute
  '/$companySlug/passenger/profile': typeof CompanySlugPassengerProfileRoute
  '/$companySlug/passenger/rewards': typeof CompanySlugPassengerRewardsRoute
  '/$companySlug/passenger/safety': typeof CompanySlugPassengerSafetyRoute
  '/$companySlug/passenger/signup': typeof CompanySlugPassengerSignupRoute
  '/$companySlug/passenger/track': typeof CompanySlugPassengerTrackRoute
  '/api/public/diag-billing': typeof ApiPublicDiagBillingRoute
  '/api/public/get-billing-rate': typeof ApiPublicGetBillingRateRoute
  '/api/public/get-portal-credential': typeof ApiPublicGetPortalCredentialRoute
  '/api/public/get-trip-pdf': typeof ApiPublicGetTripPdfRoute
  '/api/public/sms-inbound': typeof ApiPublicSmsInboundRoute
  '/$companySlug/billing/': typeof CompanySlugBillingIndexRoute
  '/$companySlug/dispatch/': typeof CompanySlugDispatchIndexRoute
  '/$companySlug/driver/': typeof CompanySlugDriverIndexRoute
  '/$companySlug/passenger/': typeof CompanySlugPassengerIndexRoute
  '/$companySlug/medicaid-trips/new': typeof CompanySlugAuthenticatedMedicaidTripsNewRoute
  '/$companySlug/payroll/$driverId': typeof CompanySlugAuthenticatedPayrollDriverIdRoute
  '/$companySlug/dispatch/routes/$routeId': typeof CompanySlugDispatchRoutesRouteIdRoute
  '/$companySlug/driver/trip/new': typeof CompanySlugDriverTripNewRoute
  '/$companySlug/passenger/book/pickup': typeof CompanySlugPassengerBookPickupRoute
  '/$companySlug/passenger/book/vehicle': typeof CompanySlugPassengerBookVehicleRoute
  '/$companySlug/payroll/': typeof CompanySlugAuthenticatedPayrollIndexRoute
  '/$companySlug/dispatch/routes/': typeof CompanySlugDispatchRoutesIndexRoute
  '/$companySlug/trips/$tripId/proof': typeof CompanySlugAuthenticatedTripsTripIdProofRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/showcase': typeof ShowcaseRoute
  '/$companySlug': typeof CompanySlugIndexRoute
  '/$companySlug/$': typeof CompanySlugSplatRoute
  '/$companySlug/login': typeof CompanySlugLoginRoute
  '/dispatch/signin': typeof DispatchSigninRoute
  '/driver/signin': typeof DriverSigninRoute
  '/owner/signin': typeof OwnerSigninRoute
  '/ride/$requestId': typeof RideRequestIdRoute
  '/track/$tripId': typeof TrackTripIdRoute
  '/owner': typeof OwnerIndexRoute
  '/$companySlug/dashboard': typeof CompanySlugAuthenticatedDashboardRoute
  '/$companySlug/drivers': typeof CompanySlugAuthenticatedDriversRoute
  '/$companySlug/events': typeof CompanySlugAuthenticatedEventsRoute
  '/$companySlug/games': typeof CompanySlugAuthenticatedGamesRoute
  '/$companySlug/incidents': typeof CompanySlugAuthenticatedIncidentsRoute
  '/$companySlug/live-ops': typeof CompanySlugAuthenticatedLiveOpsRoute
  '/$companySlug/medicaid-billing': typeof CompanySlugAuthenticatedMedicaidBillingRoute
  '/$companySlug/medicaid-trips': typeof CompanySlugAuthenticatedMedicaidTripsRouteWithChildren
  '/$companySlug/messages': typeof CompanySlugAuthenticatedMessagesRoute
  '/$companySlug/news': typeof CompanySlugAuthenticatedNewsRoute
  '/$companySlug/news-feed': typeof CompanySlugAuthenticatedNewsFeedRoute
  '/$companySlug/passengers': typeof CompanySlugAuthenticatedPassengersRoute
  '/$companySlug/planner': typeof CompanySlugAuthenticatedPlannerRoute
  '/$companySlug/reports': typeof CompanySlugAuthenticatedReportsRoute
  '/$companySlug/rewards-settings': typeof CompanySlugAuthenticatedRewardsSettingsRoute
  '/$companySlug/schedules': typeof CompanySlugAuthenticatedSchedulesRoute
  '/$companySlug/team': typeof CompanySlugAuthenticatedTeamRoute
  '/$companySlug/trips': typeof CompanySlugAuthenticatedTripsRoute
  '/$companySlug/billing/chat': typeof CompanySlugBillingChatRoute
  '/$companySlug/billing/settings': typeof CompanySlugBillingSettingsRoute
  '/$companySlug/billing/signin': typeof CompanySlugBillingSigninRoute
  '/$companySlug/dispatch/history': typeof CompanySlugDispatchHistoryRoute
  '/$companySlug/dispatch/schedule': typeof CompanySlugDispatchScheduleRoute
  '/$companySlug/dispatch/signin': typeof CompanySlugDispatchSigninRoute
  '/$companySlug/driver/earnings': typeof CompanySlugDriverEarningsRoute
  '/$companySlug/driver/expenses': typeof CompanySlugDriverExpensesRoute
  '/$companySlug/driver/history': typeof CompanySlugDriverHistoryRoute
  '/$companySlug/driver/messages': typeof CompanySlugDriverMessagesRoute
  '/$companySlug/driver/profile': typeof CompanySlugDriverProfileRoute
  '/$companySlug/driver/signin': typeof CompanySlugDriverSigninRoute
  '/$companySlug/passenger/apply': typeof CompanySlugPassengerApplyRoute
  '/$companySlug/passenger/events': typeof CompanySlugPassengerEventsRoute
  '/$companySlug/passenger/games': typeof CompanySlugPassengerGamesRoute
  '/$companySlug/passenger/news': typeof CompanySlugPassengerNewsRoute
  '/$companySlug/passenger/profile': typeof CompanySlugPassengerProfileRoute
  '/$companySlug/passenger/rewards': typeof CompanySlugPassengerRewardsRoute
  '/$companySlug/passenger/safety': typeof CompanySlugPassengerSafetyRoute
  '/$companySlug/passenger/signup': typeof CompanySlugPassengerSignupRoute
  '/$companySlug/passenger/track': typeof CompanySlugPassengerTrackRoute
  '/api/public/diag-billing': typeof ApiPublicDiagBillingRoute
  '/api/public/get-billing-rate': typeof ApiPublicGetBillingRateRoute
  '/api/public/get-portal-credential': typeof ApiPublicGetPortalCredentialRoute
  '/api/public/get-trip-pdf': typeof ApiPublicGetTripPdfRoute
  '/api/public/sms-inbound': typeof ApiPublicSmsInboundRoute
  '/$companySlug/billing': typeof CompanySlugBillingIndexRoute
  '/$companySlug/dispatch': typeof CompanySlugDispatchIndexRoute
  '/$companySlug/driver': typeof CompanySlugDriverIndexRoute
  '/$companySlug/passenger': typeof CompanySlugPassengerIndexRoute
  '/$companySlug/medicaid-trips/new': typeof CompanySlugAuthenticatedMedicaidTripsNewRoute
  '/$companySlug/payroll/$driverId': typeof CompanySlugAuthenticatedPayrollDriverIdRoute
  '/$companySlug/dispatch/routes/$routeId': typeof CompanySlugDispatchRoutesRouteIdRoute
  '/$companySlug/driver/trip/new': typeof CompanySlugDriverTripNewRoute
  '/$companySlug/passenger/book/pickup': typeof CompanySlugPassengerBookPickupRoute
  '/$companySlug/passenger/book/vehicle': typeof CompanySlugPassengerBookVehicleRoute
  '/$companySlug/payroll': typeof CompanySlugAuthenticatedPayrollIndexRoute
  '/$companySlug/dispatch/routes': typeof CompanySlugDispatchRoutesIndexRoute
  '/$companySlug/trips/$tripId/proof': typeof CompanySlugAuthenticatedTripsTripIdProofRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$companySlug': typeof CompanySlugRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/showcase': typeof ShowcaseRoute
  '/$companySlug/_authenticated': typeof CompanySlugAuthenticatedRouteRouteWithChildren
  '/$companySlug/$': typeof CompanySlugSplatRoute
  '/$companySlug/billing': typeof CompanySlugBillingRouteWithChildren
  '/$companySlug/dispatch': typeof CompanySlugDispatchRouteWithChildren
  '/$companySlug/driver': typeof CompanySlugDriverRouteWithChildren
  '/$companySlug/login': typeof CompanySlugLoginRoute
  '/$companySlug/passenger': typeof CompanySlugPassengerRouteWithChildren
  '/dispatch/signin': typeof DispatchSigninRoute
  '/driver/signin': typeof DriverSigninRoute
  '/owner/signin': typeof OwnerSigninRoute
  '/ride/$requestId': typeof RideRequestIdRoute
  '/track/$tripId': typeof TrackTripIdRoute
  '/$companySlug/': typeof CompanySlugIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/$companySlug/_authenticated/dashboard': typeof CompanySlugAuthenticatedDashboardRoute
  '/$companySlug/_authenticated/drivers': typeof CompanySlugAuthenticatedDriversRoute
  '/$companySlug/_authenticated/events': typeof CompanySlugAuthenticatedEventsRoute
  '/$companySlug/_authenticated/games': typeof CompanySlugAuthenticatedGamesRoute
  '/$companySlug/_authenticated/incidents': typeof CompanySlugAuthenticatedIncidentsRoute
  '/$companySlug/_authenticated/live-ops': typeof CompanySlugAuthenticatedLiveOpsRoute
  '/$companySlug/_authenticated/medicaid-billing': typeof CompanySlugAuthenticatedMedicaidBillingRoute
  '/$companySlug/_authenticated/medicaid-trips': typeof CompanySlugAuthenticatedMedicaidTripsRouteWithChildren
  '/$companySlug/_authenticated/messages': typeof CompanySlugAuthenticatedMessagesRoute
  '/$companySlug/_authenticated/news': typeof CompanySlugAuthenticatedNewsRoute
  '/$companySlug/_authenticated/news-feed': typeof CompanySlugAuthenticatedNewsFeedRoute
  '/$companySlug/_authenticated/passengers': typeof CompanySlugAuthenticatedPassengersRoute
  '/$companySlug/_authenticated/planner': typeof CompanySlugAuthenticatedPlannerRoute
  '/$companySlug/_authenticated/reports': typeof CompanySlugAuthenticatedReportsRoute
  '/$companySlug/_authenticated/rewards-settings': typeof CompanySlugAuthenticatedRewardsSettingsRoute
  '/$companySlug/_authenticated/schedules': typeof CompanySlugAuthenticatedSchedulesRoute
  '/$companySlug/_authenticated/team': typeof CompanySlugAuthenticatedTeamRoute
  '/$companySlug/_authenticated/trips': typeof CompanySlugAuthenticatedTripsRoute
  '/$companySlug/billing/chat': typeof CompanySlugBillingChatRoute
  '/$companySlug/billing/settings': typeof CompanySlugBillingSettingsRoute
  '/$companySlug/billing/signin': typeof CompanySlugBillingSigninRoute
  '/$companySlug/dispatch/history': typeof CompanySlugDispatchHistoryRoute
  '/$companySlug/dispatch/routes': typeof CompanySlugDispatchRoutesRouteWithChildren
  '/$companySlug/dispatch/schedule': typeof CompanySlugDispatchScheduleRoute
  '/$companySlug/dispatch/signin': typeof CompanySlugDispatchSigninRoute
  '/$companySlug/driver/earnings': typeof CompanySlugDriverEarningsRoute
  '/$companySlug/driver/expenses': typeof CompanySlugDriverExpensesRoute
  '/$companySlug/driver/history': typeof CompanySlugDriverHistoryRoute
  '/$companySlug/driver/messages': typeof CompanySlugDriverMessagesRoute
  '/$companySlug/driver/profile': typeof CompanySlugDriverProfileRoute
  '/$companySlug/driver/signin': typeof CompanySlugDriverSigninRoute
  '/$companySlug/passenger/apply': typeof CompanySlugPassengerApplyRoute
  '/$companySlug/passenger/events': typeof CompanySlugPassengerEventsRoute
  '/$companySlug/passenger/games': typeof CompanySlugPassengerGamesRoute
  '/$companySlug/passenger/news': typeof CompanySlugPassengerNewsRoute
  '/$companySlug/passenger/profile': typeof CompanySlugPassengerProfileRoute
  '/$companySlug/passenger/rewards': typeof CompanySlugPassengerRewardsRoute
  '/$companySlug/passenger/safety': typeof CompanySlugPassengerSafetyRoute
  '/$companySlug/passenger/signup': typeof CompanySlugPassengerSignupRoute
  '/$companySlug/passenger/track': typeof CompanySlugPassengerTrackRoute
  '/api/public/diag-billing': typeof ApiPublicDiagBillingRoute
  '/api/public/get-billing-rate': typeof ApiPublicGetBillingRateRoute
  '/api/public/get-portal-credential': typeof ApiPublicGetPortalCredentialRoute
  '/api/public/get-trip-pdf': typeof ApiPublicGetTripPdfRoute
  '/api/public/sms-inbound': typeof ApiPublicSmsInboundRoute
  '/$companySlug/billing/': typeof CompanySlugBillingIndexRoute
  '/$companySlug/dispatch/': typeof CompanySlugDispatchIndexRoute
  '/$companySlug/driver/': typeof CompanySlugDriverIndexRoute
  '/$companySlug/passenger/': typeof CompanySlugPassengerIndexRoute
  '/$companySlug/_authenticated/medicaid-trips/new': typeof CompanySlugAuthenticatedMedicaidTripsNewRoute
  '/$companySlug/_authenticated/payroll/$driverId': typeof CompanySlugAuthenticatedPayrollDriverIdRoute
  '/$companySlug/dispatch/routes/$routeId': typeof CompanySlugDispatchRoutesRouteIdRoute
  '/$companySlug/driver/trip/new': typeof CompanySlugDriverTripNewRoute
  '/$companySlug/passenger/book/pickup': typeof CompanySlugPassengerBookPickupRoute
  '/$companySlug/passenger/book/vehicle': typeof CompanySlugPassengerBookVehicleRoute
  '/$companySlug/_authenticated/payroll/': typeof CompanySlugAuthenticatedPayrollIndexRoute
  '/$companySlug/dispatch/routes/': typeof CompanySlugDispatchRoutesIndexRoute
  '/$companySlug/_authenticated/trips_/$tripId/proof': typeof CompanySlugAuthenticatedTripsTripIdProofRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$companySlug'
    | '/auth'
    | '/showcase'
    | '/$companySlug/$'
    | '/$companySlug/billing'
    | '/$companySlug/dispatch'
    | '/$companySlug/driver'
    | '/$companySlug/login'
    | '/$companySlug/passenger'
    | '/dispatch/signin'
    | '/driver/signin'
    | '/owner/signin'
    | '/ride/$requestId'
    | '/track/$tripId'
    | '/$companySlug/'
    | '/owner/'
    | '/$companySlug/dashboard'
    | '/$companySlug/drivers'
    | '/$companySlug/events'
    | '/$companySlug/games'
    | '/$companySlug/incidents'
    | '/$companySlug/live-ops'
    | '/$companySlug/medicaid-billing'
    | '/$companySlug/medicaid-trips'
    | '/$companySlug/messages'
    | '/$companySlug/news'
    | '/$companySlug/news-feed'
    | '/$companySlug/passengers'
    | '/$companySlug/planner'
    | '/$companySlug/reports'
    | '/$companySlug/rewards-settings'
    | '/$companySlug/schedules'
    | '/$companySlug/team'
    | '/$companySlug/trips'
    | '/$companySlug/billing/chat'
    | '/$companySlug/billing/settings'
    | '/$companySlug/billing/signin'
    | '/$companySlug/dispatch/history'
    | '/$companySlug/dispatch/routes'
    | '/$companySlug/dispatch/schedule'
    | '/$companySlug/dispatch/signin'
    | '/$companySlug/driver/earnings'
    | '/$companySlug/driver/expenses'
    | '/$companySlug/driver/history'
    | '/$companySlug/driver/messages'
    | '/$companySlug/driver/profile'
    | '/$companySlug/driver/signin'
    | '/$companySlug/passenger/apply'
    | '/$companySlug/passenger/events'
    | '/$companySlug/passenger/games'
    | '/$companySlug/passenger/news'
    | '/$companySlug/passenger/profile'
    | '/$companySlug/passenger/rewards'
    | '/$companySlug/passenger/safety'
    | '/$companySlug/passenger/signup'
    | '/$companySlug/passenger/track'
    | '/api/public/diag-billing'
    | '/api/public/get-billing-rate'
    | '/api/public/get-portal-credential'
    | '/api/public/get-trip-pdf'
    | '/api/public/sms-inbound'
    | '/$companySlug/billing/'
    | '/$companySlug/dispatch/'
    | '/$companySlug/driver/'
    | '/$companySlug/passenger/'
    | '/$companySlug/medicaid-trips/new'
    | '/$companySlug/payroll/$driverId'
    | '/$companySlug/dispatch/routes/$routeId'
    | '/$companySlug/driver/trip/new'
    | '/$companySlug/passenger/book/pickup'
    | '/$companySlug/passenger/book/vehicle'
    | '/$companySlug/payroll/'
    | '/$companySlug/dispatch/routes/'
    | '/$companySlug/trips/$tripId/proof'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/showcase'
    | '/$companySlug'
    | '/$companySlug/$'
    | '/$companySlug/login'
    | '/dispatch/signin'
    | '/driver/signin'
    | '/owner/signin'
    | '/ride/$requestId'
    | '/track/$tripId'
    | '/owner'
    | '/$companySlug/dashboard'
    | '/$companySlug/drivers'
    | '/$companySlug/events'
    | '/$companySlug/games'
    | '/$companySlug/incidents'
    | '/$companySlug/live-ops'
    | '/$companySlug/medicaid-billing'
    | '/$companySlug/medicaid-trips'
    | '/$companySlug/messages'
    | '/$companySlug/news'
    | '/$companySlug/news-feed'
    | '/$companySlug/passengers'
    | '/$companySlug/planner'
    | '/$companySlug/reports'
    | '/$companySlug/rewards-settings'
    | '/$companySlug/schedules'
    | '/$companySlug/team'
    | '/$companySlug/trips'
    | '/$companySlug/billing/chat'
    | '/$companySlug/billing/settings'
    | '/$companySlug/billing/signin'
    | '/$companySlug/dispatch/history'
    | '/$companySlug/dispatch/schedule'
    | '/$companySlug/dispatch/signin'
    | '/$companySlug/driver/earnings'
    | '/$companySlug/driver/expenses'
    | '/$companySlug/driver/history'
    | '/$companySlug/driver/messages'
    | '/$companySlug/driver/profile'
    | '/$companySlug/driver/signin'
    | '/$companySlug/passenger/apply'
    | '/$companySlug/passenger/events'
    | '/$companySlug/passenger/games'
    | '/$companySlug/passenger/news'
    | '/$companySlug/passenger/profile'
    | '/$companySlug/passenger/rewards'
    | '/$companySlug/passenger/safety'
    | '/$companySlug/passenger/signup'
    | '/$companySlug/passenger/track'
    | '/api/public/diag-billing'
    | '/api/public/get-billing-rate'
    | '/api/public/get-portal-credential'
    | '/api/public/get-trip-pdf'
    | '/api/public/sms-inbound'
    | '/$companySlug/billing'
    | '/$companySlug/dispatch'
    | '/$companySlug/driver'
    | '/$companySlug/passenger'
    | '/$companySlug/medicaid-trips/new'
    | '/$companySlug/payroll/$driverId'
    | '/$companySlug/dispatch/routes/$routeId'
    | '/$companySlug/driver/trip/new'
    | '/$companySlug/passenger/book/pickup'
    | '/$companySlug/passenger/book/vehicle'
    | '/$companySlug/payroll'
    | '/$companySlug/dispatch/routes'
    | '/$companySlug/trips/$tripId/proof'
  id:
    | '__root__'
    | '/'
    | '/$companySlug'
    | '/auth'
    | '/showcase'
    | '/$companySlug/_authenticated'
    | '/$companySlug/$'
    | '/$companySlug/billing'
    | '/$companySlug/dispatch'
    | '/$companySlug/driver'
    | '/$companySlug/login'
    | '/$companySlug/passenger'
    | '/dispatch/signin'
    | '/driver/signin'
    | '/owner/signin'
    | '/ride/$requestId'
    | '/track/$tripId'
    | '/$companySlug/'
    | '/owner/'
    | '/$companySlug/_authenticated/dashboard'
    | '/$companySlug/_authenticated/drivers'
    | '/$companySlug/_authenticated/events'
    | '/$companySlug/_authenticated/games'
    | '/$companySlug/_authenticated/incidents'
    | '/$companySlug/_authenticated/live-ops'
    | '/$companySlug/_authenticated/medicaid-billing'
    | '/$companySlug/_authenticated/medicaid-trips'
    | '/$companySlug/_authenticated/messages'
    | '/$companySlug/_authenticated/news'
    | '/$companySlug/_authenticated/news-feed'
    | '/$companySlug/_authenticated/passengers'
    | '/$companySlug/_authenticated/planner'
    | '/$companySlug/_authenticated/reports'
    | '/$companySlug/_authenticated/rewards-settings'
    | '/$companySlug/_authenticated/schedules'
    | '/$companySlug/_authenticated/team'
    | '/$companySlug/_authenticated/trips'
    | '/$companySlug/billing/chat'
    | '/$companySlug/billing/settings'
    | '/$companySlug/billing/signin'
    | '/$companySlug/dispatch/history'
    | '/$companySlug/dispatch/routes'
    | '/$companySlug/dispatch/schedule'
    | '/$companySlug/dispatch/signin'
    | '/$companySlug/driver/earnings'
    | '/$companySlug/driver/expenses'
    | '/$companySlug/driver/history'
    | '/$companySlug/driver/messages'
    | '/$companySlug/driver/profile'
    | '/$companySlug/driver/signin'
    | '/$companySlug/passenger/apply'
    | '/$companySlug/passenger/events'
    | '/$companySlug/passenger/games'
    | '/$companySlug/passenger/news'
    | '/$companySlug/passenger/profile'
    | '/$companySlug/passenger/rewards'
    | '/$companySlug/passenger/safety'
    | '/$companySlug/passenger/signup'
    | '/$companySlug/passenger/track'
    | '/api/public/diag-billing'
    | '/api/public/get-billing-rate'
    | '/api/public/get-portal-credential'
    | '/api/public/get-trip-pdf'
    | '/api/public/sms-inbound'
    | '/$companySlug/billing/'
    | '/$companySlug/dispatch/'
    | '/$companySlug/driver/'
    | '/$companySlug/passenger/'
    | '/$companySlug/_authenticated/medicaid-trips/new'
    | '/$companySlug/_authenticated/payroll/$driverId'
    | '/$companySlug/dispatch/routes/$routeId'
    | '/$companySlug/driver/trip/new'
    | '/$companySlug/passenger/book/pickup'
    | '/$companySlug/passenger/book/vehicle'
    | '/$companySlug/_authenticated/payroll/'
    | '/$companySlug/dispatch/routes/'
    | '/$companySlug/_authenticated/trips_/$tripId/proof'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanySlugRouteRoute: typeof CompanySlugRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ShowcaseRoute: typeof ShowcaseRoute
  DispatchSigninRoute: typeof DispatchSigninRoute
  DriverSigninRoute: typeof DriverSigninRoute
  OwnerSigninRoute: typeof OwnerSigninRoute
  RideRequestIdRoute: typeof RideRequestIdRoute
  TrackTripIdRoute: typeof TrackTripIdRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  ApiPublicDiagBillingRoute: typeof ApiPublicDiagBillingRoute
  ApiPublicGetBillingRateRoute: typeof ApiPublicGetBillingRateRoute
  ApiPublicGetPortalCredentialRoute: typeof ApiPublicGetPortalCredentialRoute
  ApiPublicGetTripPdfRoute: typeof ApiPublicGetTripPdfRoute
  ApiPublicSmsInboundRoute: typeof ApiPublicSmsInboundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$companySlug': {
      id: '/$companySlug'
      path: '/$companySlug'
      fullPath: '/$companySlug'
      preLoaderRoute: typeof CompanySlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$companySlug/': {
      id: '/$companySlug/'
      path: '/'
      fullPath: '/$companySlug/'
      preLoaderRoute: typeof CompanySlugIndexRouteImport
      parentRoute: typeof CompanySlugRouteRoute
    }
    '/track/$tripId': {
      id: '/track/$tripId'
      path: '/track/$tripId'
      fullPath: '/track/$tripId'
      preLoaderRoute: typeof TrackTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ride/$requestId': {
      id: '/ride/$requestId'
      path: '/ride/$requestId'
      fullPath: '/ride/$requestId'
      preLoaderRoute: typeof RideRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/signin': {
      id: '/owner/signin'
      path: '/owner/signin'
      fullPath: '/owner/signin'
      preLoaderRoute: typeof OwnerSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/signin': {
      id: '/driver/signin'
      path: '/driver/signin'
      fullPath: '/driver/signin'
      preLoaderRoute: typeof DriverSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch/signin': {
      id: '/dispatch/signin'
      path: '/dispatch/signin'
      fullPath: '/dispatch/signin'
      preLoaderRoute: typeof DispatchSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$companySlug/passenger': {
      id: '/$companySlug/passenger'
      path: '/passenger'
      fullPath: '/$companySlug/passenger'
      preLoaderRoute: typeof CompanySlugPassengerRouteImport
      parentRoute: typeof CompanySlugRouteRoute
    }
    '/$companySlug/login': {
      id: '/$companySlug/login'
      path: '/login'
      fullPath: '/$companySlug/login'
      preLoaderRoute: typeof CompanySlugLoginRouteImport
      parentRoute: typeof CompanySlugRouteRoute
    }
    '/$companySlug/driver': {
      id: '/$companySlug/driver'
      path: '/driver'
      fullPath: '/$companySlug/driver'
      preLoaderRoute: typeof CompanySlugDriverRouteImport
      parentRoute: typeof CompanySlugRouteRoute
    }
    '/$companySlug/dispatch': {
      id: '/$companySlug/dispatch'
      path: '/dispatch'
      fullPath: '/$companySlug/dispatch'
      preLoaderRoute: typeof CompanySlugDispatchRouteImport
      parentRoute: typeof CompanySlugRouteRoute
    }
    '/$companySlug/billing': {
      id: '/$companySlug/billing'
      path: '/billing'
      fullPath: '/$companySlug/billing'
      preLoaderRoute: typeof CompanySlugBillingRouteImport
      parentRoute: typeof CompanySlugRouteRoute
    }
    '/$companySlug/$': {
      id: '/$companySlug/$'
      path: '/$'
      fullPath: '/$companySlug/$'
      preLoaderRoute: typeof CompanySlugSplatRouteImport
      parentRoute: typeof CompanySlugRouteRoute
    }
    '/$companySlug/_authenticated': {
      id: '/$companySlug/_authenticated'
      path: ''
      fullPath: '/$companySlug'
      preLoaderRoute: typeof CompanySlugAuthenticatedRouteRouteImport
      parentRoute: typeof CompanySlugRouteRoute
    }
    '/$companySlug/passenger/': {
      id: '/$companySlug/passenger/'
      path: '/'
      fullPath: '/$companySlug/passenger/'
      preLoaderRoute: typeof CompanySlugPassengerIndexRouteImport
      parentRoute: typeof CompanySlugPassengerRoute
    }
    '/$companySlug/driver/': {
      id: '/$companySlug/driver/'
      path: '/'
      fullPath: '/$companySlug/driver/'
      preLoaderRoute: typeof CompanySlugDriverIndexRouteImport
      parentRoute: typeof CompanySlugDriverRoute
    }
    '/$companySlug/dispatch/': {
      id: '/$companySlug/dispatch/'
      path: '/'
      fullPath: '/$companySlug/dispatch/'
      preLoaderRoute: typeof CompanySlugDispatchIndexRouteImport
      parentRoute: typeof CompanySlugDispatchRoute
    }
    '/$companySlug/billing/': {
      id: '/$companySlug/billing/'
      path: '/'
      fullPath: '/$companySlug/billing/'
      preLoaderRoute: typeof CompanySlugBillingIndexRouteImport
      parentRoute: typeof CompanySlugBillingRoute
    }
    '/api/public/sms-inbound': {
      id: '/api/public/sms-inbound'
      path: '/api/public/sms-inbound'
      fullPath: '/api/public/sms-inbound'
      preLoaderRoute: typeof ApiPublicSmsInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/get-trip-pdf': {
      id: '/api/public/get-trip-pdf'
      path: '/api/public/get-trip-pdf'
      fullPath: '/api/public/get-trip-pdf'
      preLoaderRoute: typeof ApiPublicGetTripPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/get-portal-credential': {
      id: '/api/public/get-portal-credential'
      path: '/api/public/get-portal-credential'
      fullPath: '/api/public/get-portal-credential'
      preLoaderRoute: typeof ApiPublicGetPortalCredentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/get-billing-rate': {
      id: '/api/public/get-billing-rate'
      path: '/api/public/get-billing-rate'
      fullPath: '/api/public/get-billing-rate'
      preLoaderRoute: typeof ApiPublicGetBillingRateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diag-billing': {
      id: '/api/public/diag-billing'
      path: '/api/public/diag-billing'
      fullPath: '/api/public/diag-billing'
      preLoaderRoute: typeof ApiPublicDiagBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$companySlug/passenger/track': {
      id: '/$companySlug/passenger/track'
      path: '/track'
      fullPath: '/$companySlug/passenger/track'
      preLoaderRoute: typeof CompanySlugPassengerTrackRouteImport
      parentRoute: typeof CompanySlugPassengerRoute
    }
    '/$companySlug/passenger/signup': {
      id: '/$companySlug/passenger/signup'
      path: '/signup'
      fullPath: '/$companySlug/passenger/signup'
      preLoaderRoute: typeof CompanySlugPassengerSignupRouteImport
      parentRoute: typeof CompanySlugPassengerRoute
    }
    '/$companySlug/passenger/safety': {
      id: '/$companySlug/passenger/safety'
      path: '/safety'
      fullPath: '/$companySlug/passenger/safety'
      preLoaderRoute: typeof CompanySlugPassengerSafetyRouteImport
      parentRoute: typeof CompanySlugPassengerRoute
    }
    '/$companySlug/passenger/rewards': {
      id: '/$companySlug/passenger/rewards'
      path: '/rewards'
      fullPath: '/$companySlug/passenger/rewards'
      preLoaderRoute: typeof CompanySlugPassengerRewardsRouteImport
      parentRoute: typeof CompanySlugPassengerRoute
    }
    '/$companySlug/passenger/profile': {
      id: '/$companySlug/passenger/profile'
      path: '/profile'
      fullPath: '/$companySlug/passenger/profile'
      preLoaderRoute: typeof CompanySlugPassengerProfileRouteImport
      parentRoute: typeof CompanySlugPassengerRoute
    }
    '/$companySlug/passenger/news': {
      id: '/$companySlug/passenger/news'
      path: '/news'
      fullPath: '/$companySlug/passenger/news'
      preLoaderRoute: typeof CompanySlugPassengerNewsRouteImport
      parentRoute: typeof CompanySlugPassengerRoute
    }
    '/$companySlug/passenger/games': {
      id: '/$companySlug/passenger/games'
      path: '/games'
      fullPath: '/$companySlug/passenger/games'
      preLoaderRoute: typeof CompanySlugPassengerGamesRouteImport
      parentRoute: typeof CompanySlugPassengerRoute
    }
    '/$companySlug/passenger/events': {
      id: '/$companySlug/passenger/events'
      path: '/events'
      fullPath: '/$companySlug/passenger/events'
      preLoaderRoute: typeof CompanySlugPassengerEventsRouteImport
      parentRoute: typeof CompanySlugPassengerRoute
    }
    '/$companySlug/passenger/apply': {
      id: '/$companySlug/passenger/apply'
      path: '/apply'
      fullPath: '/$companySlug/passenger/apply'
      preLoaderRoute: typeof CompanySlugPassengerApplyRouteImport
      parentRoute: typeof CompanySlugPassengerRoute
    }
    '/$companySlug/driver/signin': {
      id: '/$companySlug/driver/signin'
      path: '/signin'
      fullPath: '/$companySlug/driver/signin'
      preLoaderRoute: typeof CompanySlugDriverSigninRouteImport
      parentRoute: typeof CompanySlugDriverRoute
    }
    '/$companySlug/driver/profile': {
      id: '/$companySlug/driver/profile'
      path: '/profile'
      fullPath: '/$companySlug/driver/profile'
      preLoaderRoute: typeof CompanySlugDriverProfileRouteImport
      parentRoute: typeof CompanySlugDriverRoute
    }
    '/$companySlug/driver/messages': {
      id: '/$companySlug/driver/messages'
      path: '/messages'
      fullPath: '/$companySlug/driver/messages'
      preLoaderRoute: typeof CompanySlugDriverMessagesRouteImport
      parentRoute: typeof CompanySlugDriverRoute
    }
    '/$companySlug/driver/history': {
      id: '/$companySlug/driver/history'
      path: '/history'
      fullPath: '/$companySlug/driver/history'
      preLoaderRoute: typeof CompanySlugDriverHistoryRouteImport
      parentRoute: typeof CompanySlugDriverRoute
    }
    '/$companySlug/driver/expenses': {
      id: '/$companySlug/driver/expenses'
      path: '/expenses'
      fullPath: '/$companySlug/driver/expenses'
      preLoaderRoute: typeof CompanySlugDriverExpensesRouteImport
      parentRoute: typeof CompanySlugDriverRoute
    }
    '/$companySlug/driver/earnings': {
      id: '/$companySlug/driver/earnings'
      path: '/earnings'
      fullPath: '/$companySlug/driver/earnings'
      preLoaderRoute: typeof CompanySlugDriverEarningsRouteImport
      parentRoute: typeof CompanySlugDriverRoute
    }
    '/$companySlug/dispatch/signin': {
      id: '/$companySlug/dispatch/signin'
      path: '/signin'
      fullPath: '/$companySlug/dispatch/signin'
      preLoaderRoute: typeof CompanySlugDispatchSigninRouteImport
      parentRoute: typeof CompanySlugDispatchRoute
    }
    '/$companySlug/dispatch/schedule': {
      id: '/$companySlug/dispatch/schedule'
      path: '/schedule'
      fullPath: '/$companySlug/dispatch/schedule'
      preLoaderRoute: typeof CompanySlugDispatchScheduleRouteImport
      parentRoute: typeof CompanySlugDispatchRoute
    }
    '/$companySlug/dispatch/routes': {
      id: '/$companySlug/dispatch/routes'
      path: '/routes'
      fullPath: '/$companySlug/dispatch/routes'
      preLoaderRoute: typeof CompanySlugDispatchRoutesRouteImport
      parentRoute: typeof CompanySlugDispatchRoute
    }
    '/$companySlug/dispatch/history': {
      id: '/$companySlug/dispatch/history'
      path: '/history'
      fullPath: '/$companySlug/dispatch/history'
      preLoaderRoute: typeof CompanySlugDispatchHistoryRouteImport
      parentRoute: typeof CompanySlugDispatchRoute
    }
    '/$companySlug/billing/signin': {
      id: '/$companySlug/billing/signin'
      path: '/signin'
      fullPath: '/$companySlug/billing/signin'
      preLoaderRoute: typeof CompanySlugBillingSigninRouteImport
      parentRoute: typeof CompanySlugBillingRoute
    }
    '/$companySlug/billing/settings': {
      id: '/$companySlug/billing/settings'
      path: '/settings'
      fullPath: '/$companySlug/billing/settings'
      preLoaderRoute: typeof CompanySlugBillingSettingsRouteImport
      parentRoute: typeof CompanySlugBillingRoute
    }
    '/$companySlug/billing/chat': {
      id: '/$companySlug/billing/chat'
      path: '/chat'
      fullPath: '/$companySlug/billing/chat'
      preLoaderRoute: typeof CompanySlugBillingChatRouteImport
      parentRoute: typeof CompanySlugBillingRoute
    }
    '/$companySlug/_authenticated/trips': {
      id: '/$companySlug/_authenticated/trips'
      path: '/trips'
      fullPath: '/$companySlug/trips'
      preLoaderRoute: typeof CompanySlugAuthenticatedTripsRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
    '/$companySlug/_authenticated/team': {
      id: '/$companySlug/_authenticated/team'
      path: '/team'
      fullPath: '/$companySlug/team'
      preLoaderRoute: typeof CompanySlugAuthenticatedTeamRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
    '/$companySlug/_authenticated/schedules': {
      id: '/$companySlug/_authenticated/schedules'
      path: '/schedules'
      fullPath: '/$companySlug/schedules'
      preLoaderRoute: typeof CompanySlugAuthenticatedSchedulesRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
    '/$companySlug/_authenticated/rewards-settings': {
      id: '/$companySlug/_authenticated/rewards-settings'
      path: '/rewards-settings'
      fullPath: '/$companySlug/rewards-settings'
      preLoaderRoute: typeof CompanySlugAuthenticatedRewardsSettingsRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
    '/$companySlug/_authenticated/reports': {
      id: '/$companySlug/_authenticated/reports'
      path: '/reports'
      fullPath: '/$companySlug/reports'
      preLoaderRoute: typeof CompanySlugAuthenticatedReportsRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
    '/$companySlug/_authenticated/planner': {
      id: '/$companySlug/_authenticated/planner'
      path: '/planner'
      fullPath: '/$companySlug/planner'
      preLoaderRoute: typeof CompanySlugAuthenticatedPlannerRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
    '/$companySlug/_authenticated/passengers': {
      id: '/$companySlug/_authenticated/passengers'
      path: '/passengers'
      fullPath: '/$companySlug/passengers'
      preLoaderRoute: typeof CompanySlugAuthenticatedPassengersRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
    '/$companySlug/_authenticated/news-feed': {
      id: '/$companySlug/_authenticated/news-feed'
      path: '/news-feed'
      fullPath: '/$companySlug/news-feed'
      preLoaderRoute: typeof CompanySlugAuthenticatedNewsFeedRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
    '/$companySlug/_authenticated/news': {
      id: '/$companySlug/_authenticated/news'
      path: '/news'
      fullPath: '/$companySlug/news'
      preLoaderRoute: typeof CompanySlugAuthenticatedNewsRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
    '/$companySlug/_authenticated/messages': {
      id: '/$companySlug/_authenticated/messages'
      path: '/messages'
      fullPath: '/$companySlug/messages'
      preLoaderRoute: typeof CompanySlugAuthenticatedMessagesRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
    '/$companySlug/_authenticated/medicaid-trips': {
      id: '/$companySlug/_authenticated/medicaid-trips'
      path: '/medicaid-trips'
      fullPath: '/$companySlug/medicaid-trips'
      preLoaderRoute: typeof CompanySlugAuthenticatedMedicaidTripsRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
    '/$companySlug/_authenticated/medicaid-billing': {
      id: '/$companySlug/_authenticated/medicaid-billing'
      path: '/medicaid-billing'
      fullPath: '/$companySlug/medicaid-billing'
      preLoaderRoute: typeof CompanySlugAuthenticatedMedicaidBillingRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
    '/$companySlug/_authenticated/live-ops': {
      id: '/$companySlug/_authenticated/live-ops'
      path: '/live-ops'
      fullPath: '/$companySlug/live-ops'
      preLoaderRoute: typeof CompanySlugAuthenticatedLiveOpsRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
    '/$companySlug/_authenticated/incidents': {
      id: '/$companySlug/_authenticated/incidents'
      path: '/incidents'
      fullPath: '/$companySlug/incidents'
      preLoaderRoute: typeof CompanySlugAuthenticatedIncidentsRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
    '/$companySlug/_authenticated/games': {
      id: '/$companySlug/_authenticated/games'
      path: '/games'
      fullPath: '/$companySlug/games'
      preLoaderRoute: typeof CompanySlugAuthenticatedGamesRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
    '/$companySlug/_authenticated/events': {
      id: '/$companySlug/_authenticated/events'
      path: '/events'
      fullPath: '/$companySlug/events'
      preLoaderRoute: typeof CompanySlugAuthenticatedEventsRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
    '/$companySlug/_authenticated/drivers': {
      id: '/$companySlug/_authenticated/drivers'
      path: '/drivers'
      fullPath: '/$companySlug/drivers'
      preLoaderRoute: typeof CompanySlugAuthenticatedDriversRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
    '/$companySlug/_authenticated/dashboard': {
      id: '/$companySlug/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/$companySlug/dashboard'
      preLoaderRoute: typeof CompanySlugAuthenticatedDashboardRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
    '/$companySlug/dispatch/routes/': {
      id: '/$companySlug/dispatch/routes/'
      path: '/'
      fullPath: '/$companySlug/dispatch/routes/'
      preLoaderRoute: typeof CompanySlugDispatchRoutesIndexRouteImport
      parentRoute: typeof CompanySlugDispatchRoutesRoute
    }
    '/$companySlug/_authenticated/payroll/': {
      id: '/$companySlug/_authenticated/payroll/'
      path: '/payroll'
      fullPath: '/$companySlug/payroll/'
      preLoaderRoute: typeof CompanySlugAuthenticatedPayrollIndexRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
    '/$companySlug/passenger/book/vehicle': {
      id: '/$companySlug/passenger/book/vehicle'
      path: '/book/vehicle'
      fullPath: '/$companySlug/passenger/book/vehicle'
      preLoaderRoute: typeof CompanySlugPassengerBookVehicleRouteImport
      parentRoute: typeof CompanySlugPassengerRoute
    }
    '/$companySlug/passenger/book/pickup': {
      id: '/$companySlug/passenger/book/pickup'
      path: '/book/pickup'
      fullPath: '/$companySlug/passenger/book/pickup'
      preLoaderRoute: typeof CompanySlugPassengerBookPickupRouteImport
      parentRoute: typeof CompanySlugPassengerRoute
    }
    '/$companySlug/driver/trip/new': {
      id: '/$companySlug/driver/trip/new'
      path: '/trip/new'
      fullPath: '/$companySlug/driver/trip/new'
      preLoaderRoute: typeof CompanySlugDriverTripNewRouteImport
      parentRoute: typeof CompanySlugDriverRoute
    }
    '/$companySlug/dispatch/routes/$routeId': {
      id: '/$companySlug/dispatch/routes/$routeId'
      path: '/$routeId'
      fullPath: '/$companySlug/dispatch/routes/$routeId'
      preLoaderRoute: typeof CompanySlugDispatchRoutesRouteIdRouteImport
      parentRoute: typeof CompanySlugDispatchRoutesRoute
    }
    '/$companySlug/_authenticated/payroll/$driverId': {
      id: '/$companySlug/_authenticated/payroll/$driverId'
      path: '/payroll/$driverId'
      fullPath: '/$companySlug/payroll/$driverId'
      preLoaderRoute: typeof CompanySlugAuthenticatedPayrollDriverIdRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
    '/$companySlug/_authenticated/medicaid-trips/new': {
      id: '/$companySlug/_authenticated/medicaid-trips/new'
      path: '/new'
      fullPath: '/$companySlug/medicaid-trips/new'
      preLoaderRoute: typeof CompanySlugAuthenticatedMedicaidTripsNewRouteImport
      parentRoute: typeof CompanySlugAuthenticatedMedicaidTripsRoute
    }
    '/$companySlug/_authenticated/trips_/$tripId/proof': {
      id: '/$companySlug/_authenticated/trips_/$tripId/proof'
      path: '/trips/$tripId/proof'
      fullPath: '/$companySlug/trips/$tripId/proof'
      preLoaderRoute: typeof CompanySlugAuthenticatedTripsTripIdProofRouteImport
      parentRoute: typeof CompanySlugAuthenticatedRouteRoute
    }
  }
}

interface CompanySlugAuthenticatedMedicaidTripsRouteChildren {
  CompanySlugAuthenticatedMedicaidTripsNewRoute: typeof CompanySlugAuthenticatedMedicaidTripsNewRoute
}

const CompanySlugAuthenticatedMedicaidTripsRouteChildren: CompanySlugAuthenticatedMedicaidTripsRouteChildren =
  {
    CompanySlugAuthenticatedMedicaidTripsNewRoute:
      CompanySlugAuthenticatedMedicaidTripsNewRoute,
  }

const CompanySlugAuthenticatedMedicaidTripsRouteWithChildren =
  CompanySlugAuthenticatedMedicaidTripsRoute._addFileChildren(
    CompanySlugAuthenticatedMedicaidTripsRouteChildren,
  )

interface CompanySlugAuthenticatedRouteRouteChildren {
  CompanySlugAuthenticatedDashboardRoute: typeof CompanySlugAuthenticatedDashboardRoute
  CompanySlugAuthenticatedDriversRoute: typeof CompanySlugAuthenticatedDriversRoute
  CompanySlugAuthenticatedEventsRoute: typeof CompanySlugAuthenticatedEventsRoute
  CompanySlugAuthenticatedGamesRoute: typeof CompanySlugAuthenticatedGamesRoute
  CompanySlugAuthenticatedIncidentsRoute: typeof CompanySlugAuthenticatedIncidentsRoute
  CompanySlugAuthenticatedLiveOpsRoute: typeof CompanySlugAuthenticatedLiveOpsRoute
  CompanySlugAuthenticatedMedicaidBillingRoute: typeof CompanySlugAuthenticatedMedicaidBillingRoute
  CompanySlugAuthenticatedMedicaidTripsRoute: typeof CompanySlugAuthenticatedMedicaidTripsRouteWithChildren
  CompanySlugAuthenticatedMessagesRoute: typeof CompanySlugAuthenticatedMessagesRoute
  CompanySlugAuthenticatedNewsRoute: typeof CompanySlugAuthenticatedNewsRoute
  CompanySlugAuthenticatedNewsFeedRoute: typeof CompanySlugAuthenticatedNewsFeedRoute
  CompanySlugAuthenticatedPassengersRoute: typeof CompanySlugAuthenticatedPassengersRoute
  CompanySlugAuthenticatedPlannerRoute: typeof CompanySlugAuthenticatedPlannerRoute
  CompanySlugAuthenticatedReportsRoute: typeof CompanySlugAuthenticatedReportsRoute
  CompanySlugAuthenticatedRewardsSettingsRoute: typeof CompanySlugAuthenticatedRewardsSettingsRoute
  CompanySlugAuthenticatedSchedulesRoute: typeof CompanySlugAuthenticatedSchedulesRoute
  CompanySlugAuthenticatedTeamRoute: typeof CompanySlugAuthenticatedTeamRoute
  CompanySlugAuthenticatedTripsRoute: typeof CompanySlugAuthenticatedTripsRoute
  CompanySlugAuthenticatedPayrollDriverIdRoute: typeof CompanySlugAuthenticatedPayrollDriverIdRoute
  CompanySlugAuthenticatedPayrollIndexRoute: typeof CompanySlugAuthenticatedPayrollIndexRoute
  CompanySlugAuthenticatedTripsTripIdProofRoute: typeof CompanySlugAuthenticatedTripsTripIdProofRoute
}

const CompanySlugAuthenticatedRouteRouteChildren: CompanySlugAuthenticatedRouteRouteChildren =
  {
    CompanySlugAuthenticatedDashboardRoute:
      CompanySlugAuthenticatedDashboardRoute,
    CompanySlugAuthenticatedDriversRoute: CompanySlugAuthenticatedDriversRoute,
    CompanySlugAuthenticatedEventsRoute: CompanySlugAuthenticatedEventsRoute,
    CompanySlugAuthenticatedGamesRoute: CompanySlugAuthenticatedGamesRoute,
    CompanySlugAuthenticatedIncidentsRoute:
      CompanySlugAuthenticatedIncidentsRoute,
    CompanySlugAuthenticatedLiveOpsRoute: CompanySlugAuthenticatedLiveOpsRoute,
    CompanySlugAuthenticatedMedicaidBillingRoute:
      CompanySlugAuthenticatedMedicaidBillingRoute,
    CompanySlugAuthenticatedMedicaidTripsRoute:
      CompanySlugAuthenticatedMedicaidTripsRouteWithChildren,
    CompanySlugAuthenticatedMessagesRoute:
      CompanySlugAuthenticatedMessagesRoute,
    CompanySlugAuthenticatedNewsRoute: CompanySlugAuthenticatedNewsRoute,
    CompanySlugAuthenticatedNewsFeedRoute:
      CompanySlugAuthenticatedNewsFeedRoute,
    CompanySlugAuthenticatedPassengersRoute:
      CompanySlugAuthenticatedPassengersRoute,
    CompanySlugAuthenticatedPlannerRoute: CompanySlugAuthenticatedPlannerRoute,
    CompanySlugAuthenticatedReportsRoute: CompanySlugAuthenticatedReportsRoute,
    CompanySlugAuthenticatedRewardsSettingsRoute:
      CompanySlugAuthenticatedRewardsSettingsRoute,
    CompanySlugAuthenticatedSchedulesRoute:
      CompanySlugAuthenticatedSchedulesRoute,
    CompanySlugAuthenticatedTeamRoute: CompanySlugAuthenticatedTeamRoute,
    CompanySlugAuthenticatedTripsRoute: CompanySlugAuthenticatedTripsRoute,
    CompanySlugAuthenticatedPayrollDriverIdRoute:
      CompanySlugAuthenticatedPayrollDriverIdRoute,
    CompanySlugAuthenticatedPayrollIndexRoute:
      CompanySlugAuthenticatedPayrollIndexRoute,
    CompanySlugAuthenticatedTripsTripIdProofRoute:
      CompanySlugAuthenticatedTripsTripIdProofRoute,
  }

const CompanySlugAuthenticatedRouteRouteWithChildren =
  CompanySlugAuthenticatedRouteRoute._addFileChildren(
    CompanySlugAuthenticatedRouteRouteChildren,
  )

interface CompanySlugBillingRouteChildren {
  CompanySlugBillingChatRoute: typeof CompanySlugBillingChatRoute
  CompanySlugBillingSettingsRoute: typeof CompanySlugBillingSettingsRoute
  CompanySlugBillingSigninRoute: typeof CompanySlugBillingSigninRoute
  CompanySlugBillingIndexRoute: typeof CompanySlugBillingIndexRoute
}

const CompanySlugBillingRouteChildren: CompanySlugBillingRouteChildren = {
  CompanySlugBillingChatRoute: CompanySlugBillingChatRoute,
  CompanySlugBillingSettingsRoute: CompanySlugBillingSettingsRoute,
  CompanySlugBillingSigninRoute: CompanySlugBillingSigninRoute,
  CompanySlugBillingIndexRoute: CompanySlugBillingIndexRoute,
}

const CompanySlugBillingRouteWithChildren =
  CompanySlugBillingRoute._addFileChildren(CompanySlugBillingRouteChildren)

interface CompanySlugDispatchRoutesRouteChildren {
  CompanySlugDispatchRoutesRouteIdRoute: typeof CompanySlugDispatchRoutesRouteIdRoute
  CompanySlugDispatchRoutesIndexRoute: typeof CompanySlugDispatchRoutesIndexRoute
}

const CompanySlugDispatchRoutesRouteChildren: CompanySlugDispatchRoutesRouteChildren =
  {
    CompanySlugDispatchRoutesRouteIdRoute:
      CompanySlugDispatchRoutesRouteIdRoute,
    CompanySlugDispatchRoutesIndexRoute: CompanySlugDispatchRoutesIndexRoute,
  }

const CompanySlugDispatchRoutesRouteWithChildren =
  CompanySlugDispatchRoutesRoute._addFileChildren(
    CompanySlugDispatchRoutesRouteChildren,
  )

interface CompanySlugDispatchRouteChildren {
  CompanySlugDispatchHistoryRoute: typeof CompanySlugDispatchHistoryRoute
  CompanySlugDispatchRoutesRoute: typeof CompanySlugDispatchRoutesRouteWithChildren
  CompanySlugDispatchScheduleRoute: typeof CompanySlugDispatchScheduleRoute
  CompanySlugDispatchSigninRoute: typeof CompanySlugDispatchSigninRoute
  CompanySlugDispatchIndexRoute: typeof CompanySlugDispatchIndexRoute
}

const CompanySlugDispatchRouteChildren: CompanySlugDispatchRouteChildren = {
  CompanySlugDispatchHistoryRoute: CompanySlugDispatchHistoryRoute,
  CompanySlugDispatchRoutesRoute: CompanySlugDispatchRoutesRouteWithChildren,
  CompanySlugDispatchScheduleRoute: CompanySlugDispatchScheduleRoute,
  CompanySlugDispatchSigninRoute: CompanySlugDispatchSigninRoute,
  CompanySlugDispatchIndexRoute: CompanySlugDispatchIndexRoute,
}

const CompanySlugDispatchRouteWithChildren =
  CompanySlugDispatchRoute._addFileChildren(CompanySlugDispatchRouteChildren)

interface CompanySlugDriverRouteChildren {
  CompanySlugDriverEarningsRoute: typeof CompanySlugDriverEarningsRoute
  CompanySlugDriverExpensesRoute: typeof CompanySlugDriverExpensesRoute
  CompanySlugDriverHistoryRoute: typeof CompanySlugDriverHistoryRoute
  CompanySlugDriverMessagesRoute: typeof CompanySlugDriverMessagesRoute
  CompanySlugDriverProfileRoute: typeof CompanySlugDriverProfileRoute
  CompanySlugDriverSigninRoute: typeof CompanySlugDriverSigninRoute
  CompanySlugDriverIndexRoute: typeof CompanySlugDriverIndexRoute
  CompanySlugDriverTripNewRoute: typeof CompanySlugDriverTripNewRoute
}

const CompanySlugDriverRouteChildren: CompanySlugDriverRouteChildren = {
  CompanySlugDriverEarningsRoute: CompanySlugDriverEarningsRoute,
  CompanySlugDriverExpensesRoute: CompanySlugDriverExpensesRoute,
  CompanySlugDriverHistoryRoute: CompanySlugDriverHistoryRoute,
  CompanySlugDriverMessagesRoute: CompanySlugDriverMessagesRoute,
  CompanySlugDriverProfileRoute: CompanySlugDriverProfileRoute,
  CompanySlugDriverSigninRoute: CompanySlugDriverSigninRoute,
  CompanySlugDriverIndexRoute: CompanySlugDriverIndexRoute,
  CompanySlugDriverTripNewRoute: CompanySlugDriverTripNewRoute,
}

const CompanySlugDriverRouteWithChildren =
  CompanySlugDriverRoute._addFileChildren(CompanySlugDriverRouteChildren)

interface CompanySlugPassengerRouteChildren {
  CompanySlugPassengerApplyRoute: typeof CompanySlugPassengerApplyRoute
  CompanySlugPassengerEventsRoute: typeof CompanySlugPassengerEventsRoute
  CompanySlugPassengerGamesRoute: typeof CompanySlugPassengerGamesRoute
  CompanySlugPassengerNewsRoute: typeof CompanySlugPassengerNewsRoute
  CompanySlugPassengerProfileRoute: typeof CompanySlugPassengerProfileRoute
  CompanySlugPassengerRewardsRoute: typeof CompanySlugPassengerRewardsRoute
  CompanySlugPassengerSafetyRoute: typeof CompanySlugPassengerSafetyRoute
  CompanySlugPassengerSignupRoute: typeof CompanySlugPassengerSignupRoute
  CompanySlugPassengerTrackRoute: typeof CompanySlugPassengerTrackRoute
  CompanySlugPassengerIndexRoute: typeof CompanySlugPassengerIndexRoute
  CompanySlugPassengerBookPickupRoute: typeof CompanySlugPassengerBookPickupRoute
  CompanySlugPassengerBookVehicleRoute: typeof CompanySlugPassengerBookVehicleRoute
}

const CompanySlugPassengerRouteChildren: CompanySlugPassengerRouteChildren = {
  CompanySlugPassengerApplyRoute: CompanySlugPassengerApplyRoute,
  CompanySlugPassengerEventsRoute: CompanySlugPassengerEventsRoute,
  CompanySlugPassengerGamesRoute: CompanySlugPassengerGamesRoute,
  CompanySlugPassengerNewsRoute: CompanySlugPassengerNewsRoute,
  CompanySlugPassengerProfileRoute: CompanySlugPassengerProfileRoute,
  CompanySlugPassengerRewardsRoute: CompanySlugPassengerRewardsRoute,
  CompanySlugPassengerSafetyRoute: CompanySlugPassengerSafetyRoute,
  CompanySlugPassengerSignupRoute: CompanySlugPassengerSignupRoute,
  CompanySlugPassengerTrackRoute: CompanySlugPassengerTrackRoute,
  CompanySlugPassengerIndexRoute: CompanySlugPassengerIndexRoute,
  CompanySlugPassengerBookPickupRoute: CompanySlugPassengerBookPickupRoute,
  CompanySlugPassengerBookVehicleRoute: CompanySlugPassengerBookVehicleRoute,
}

const CompanySlugPassengerRouteWithChildren =
  CompanySlugPassengerRoute._addFileChildren(CompanySlugPassengerRouteChildren)

interface CompanySlugRouteRouteChildren {
  CompanySlugAuthenticatedRouteRoute: typeof CompanySlugAuthenticatedRouteRouteWithChildren
  CompanySlugSplatRoute: typeof CompanySlugSplatRoute
  CompanySlugBillingRoute: typeof CompanySlugBillingRouteWithChildren
  CompanySlugDispatchRoute: typeof CompanySlugDispatchRouteWithChildren
  CompanySlugDriverRoute: typeof CompanySlugDriverRouteWithChildren
  CompanySlugLoginRoute: typeof CompanySlugLoginRoute
  CompanySlugPassengerRoute: typeof CompanySlugPassengerRouteWithChildren
  CompanySlugIndexRoute: typeof CompanySlugIndexRoute
}

const CompanySlugRouteRouteChildren: CompanySlugRouteRouteChildren = {
  CompanySlugAuthenticatedRouteRoute:
    CompanySlugAuthenticatedRouteRouteWithChildren,
  CompanySlugSplatRoute: CompanySlugSplatRoute,
  CompanySlugBillingRoute: CompanySlugBillingRouteWithChildren,
  CompanySlugDispatchRoute: CompanySlugDispatchRouteWithChildren,
  CompanySlugDriverRoute: CompanySlugDriverRouteWithChildren,
  CompanySlugLoginRoute: CompanySlugLoginRoute,
  CompanySlugPassengerRoute: CompanySlugPassengerRouteWithChildren,
  CompanySlugIndexRoute: CompanySlugIndexRoute,
}

const CompanySlugRouteRouteWithChildren =
  CompanySlugRouteRoute._addFileChildren(CompanySlugRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanySlugRouteRoute: CompanySlugRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ShowcaseRoute: ShowcaseRoute,
  DispatchSigninRoute: DispatchSigninRoute,
  DriverSigninRoute: DriverSigninRoute,
  OwnerSigninRoute: OwnerSigninRoute,
  RideRequestIdRoute: RideRequestIdRoute,
  TrackTripIdRoute: TrackTripIdRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  ApiPublicDiagBillingRoute: ApiPublicDiagBillingRoute,
  ApiPublicGetBillingRateRoute: ApiPublicGetBillingRateRoute,
  ApiPublicGetPortalCredentialRoute: ApiPublicGetPortalCredentialRoute,
  ApiPublicGetTripPdfRoute: ApiPublicGetTripPdfRoute,
  ApiPublicSmsInboundRoute: ApiPublicSmsInboundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
