/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PassengerRouteImport } from './routes/passenger'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PassengerIndexRouteImport } from './routes/passenger.index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as TrackTripIdRouteImport } from './routes/track.$tripId'
import { Route as PassengerNewsRouteImport } from './routes/passenger.news'
import { Route as PassengerGamesRouteImport } from './routes/passenger.games'
import { Route as PassengerApplyRouteImport } from './routes/passenger.apply'
import { Route as DriverSigninRouteImport } from './routes/driver.signin'
import { Route as DriverProfileRouteImport } from './routes/driver.profile'
import { Route as DriverMessagesRouteImport } from './routes/driver.messages'
import { Route as DriverHistoryRouteImport } from './routes/driver.history'
import { Route as DriverEarningsRouteImport } from './routes/driver.earnings'
import { Route as AuthenticatedTripsRouteImport } from './routes/_authenticated/trips'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSchedulesRouteImport } from './routes/_authenticated/schedules'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPassengersRouteImport } from './routes/_authenticated/passengers'
import { Route as AuthenticatedNewsFeedRouteImport } from './routes/_authenticated/news-feed'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated/news'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMedicaidTripsRouteImport } from './routes/_authenticated/medicaid-trips'
import { Route as AuthenticatedMedicaidBillingRouteImport } from './routes/_authenticated/medicaid-billing'
import { Route as AuthenticatedLiveOpsRouteImport } from './routes/_authenticated/live-ops'
import { Route as AuthenticatedIncidentsRouteImport } from './routes/_authenticated/incidents'
import { Route as AuthenticatedGamesRouteImport } from './routes/_authenticated/games'
import { Route as AuthenticatedDriversRouteImport } from './routes/_authenticated/drivers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedPayrollDriverIdRouteImport } from './routes/_authenticated/payroll.$driverId'
import { Route as AuthenticatedMedicaidTripsNewRouteImport } from './routes/_authenticated/medicaid-trips.new'

const PassengerRoute = PassengerRouteImport.update({
  id: '/passenger',
  path: '/passenger',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerIndexRoute = PassengerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PassengerRoute,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const TrackTripIdRoute = TrackTripIdRouteImport.update({
  id: '/track/$tripId',
  path: '/track/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerNewsRoute = PassengerNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => PassengerRoute,
} as any)
const PassengerGamesRoute = PassengerGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => PassengerRoute,
} as any)
const PassengerApplyRoute = PassengerApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => PassengerRoute,
} as any)
const DriverSigninRoute = DriverSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => DriverRoute,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DriverRoute,
} as any)
const DriverMessagesRoute = DriverMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DriverRoute,
} as any)
const DriverHistoryRoute = DriverHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DriverRoute,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DriverRoute,
} as any)
const AuthenticatedTripsRoute = AuthenticatedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchedulesRoute = AuthenticatedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPassengersRoute = AuthenticatedPassengersRouteImport.update({
  id: '/passengers',
  path: '/passengers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsFeedRoute = AuthenticatedNewsFeedRouteImport.update({
  id: '/news-feed',
  path: '/news-feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMedicaidTripsRoute =
  AuthenticatedMedicaidTripsRouteImport.update({
    id: '/medicaid-trips',
    path: '/medicaid-trips',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMedicaidBillingRoute =
  AuthenticatedMedicaidBillingRouteImport.update({
    id: '/medicaid-billing',
    path: '/medicaid-billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLiveOpsRoute = AuthenticatedLiveOpsRouteImport.update({
  id: '/live-ops',
  path: '/live-ops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIncidentsRoute = AuthenticatedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesRoute = AuthenticatedGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriversRoute = AuthenticatedDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayrollDriverIdRoute =
  AuthenticatedPayrollDriverIdRouteImport.update({
    id: '/payroll/$driverId',
    path: '/payroll/$driverId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMedicaidTripsNewRoute =
  AuthenticatedMedicaidTripsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedMedicaidTripsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/driver': typeof DriverRouteWithChildren
  '/passenger': typeof PassengerRouteWithChildren
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/games': typeof AuthenticatedGamesRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/live-ops': typeof AuthenticatedLiveOpsRoute
  '/medicaid-billing': typeof AuthenticatedMedicaidBillingRoute
  '/medicaid-trips': typeof AuthenticatedMedicaidTripsRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/news': typeof AuthenticatedNewsRoute
  '/news-feed': typeof AuthenticatedNewsFeedRoute
  '/passengers': typeof AuthenticatedPassengersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/team': typeof AuthenticatedTeamRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/messages': typeof DriverMessagesRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/signin': typeof DriverSigninRoute
  '/passenger/apply': typeof PassengerApplyRoute
  '/passenger/games': typeof PassengerGamesRoute
  '/passenger/news': typeof PassengerNewsRoute
  '/track/$tripId': typeof TrackTripIdRoute
  '/driver/': typeof DriverIndexRoute
  '/passenger/': typeof PassengerIndexRoute
  '/medicaid-trips/new': typeof AuthenticatedMedicaidTripsNewRoute
  '/payroll/$driverId': typeof AuthenticatedPayrollDriverIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/games': typeof AuthenticatedGamesRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/live-ops': typeof AuthenticatedLiveOpsRoute
  '/medicaid-billing': typeof AuthenticatedMedicaidBillingRoute
  '/medicaid-trips': typeof AuthenticatedMedicaidTripsRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/news': typeof AuthenticatedNewsRoute
  '/news-feed': typeof AuthenticatedNewsFeedRoute
  '/passengers': typeof AuthenticatedPassengersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/team': typeof AuthenticatedTeamRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/messages': typeof DriverMessagesRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/signin': typeof DriverSigninRoute
  '/passenger/apply': typeof PassengerApplyRoute
  '/passenger/games': typeof PassengerGamesRoute
  '/passenger/news': typeof PassengerNewsRoute
  '/track/$tripId': typeof TrackTripIdRoute
  '/driver': typeof DriverIndexRoute
  '/passenger': typeof PassengerIndexRoute
  '/medicaid-trips/new': typeof AuthenticatedMedicaidTripsNewRoute
  '/payroll/$driverId': typeof AuthenticatedPayrollDriverIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/driver': typeof DriverRouteWithChildren
  '/passenger': typeof PassengerRouteWithChildren
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/drivers': typeof AuthenticatedDriversRoute
  '/_authenticated/games': typeof AuthenticatedGamesRoute
  '/_authenticated/incidents': typeof AuthenticatedIncidentsRoute
  '/_authenticated/live-ops': typeof AuthenticatedLiveOpsRoute
  '/_authenticated/medicaid-billing': typeof AuthenticatedMedicaidBillingRoute
  '/_authenticated/medicaid-trips': typeof AuthenticatedMedicaidTripsRouteWithChildren
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/news': typeof AuthenticatedNewsRoute
  '/_authenticated/news-feed': typeof AuthenticatedNewsFeedRoute
  '/_authenticated/passengers': typeof AuthenticatedPassengersRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/schedules': typeof AuthenticatedSchedulesRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/trips': typeof AuthenticatedTripsRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/messages': typeof DriverMessagesRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/signin': typeof DriverSigninRoute
  '/passenger/apply': typeof PassengerApplyRoute
  '/passenger/games': typeof PassengerGamesRoute
  '/passenger/news': typeof PassengerNewsRoute
  '/track/$tripId': typeof TrackTripIdRoute
  '/driver/': typeof DriverIndexRoute
  '/passenger/': typeof PassengerIndexRoute
  '/_authenticated/medicaid-trips/new': typeof AuthenticatedMedicaidTripsNewRoute
  '/_authenticated/payroll/$driverId': typeof AuthenticatedPayrollDriverIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/driver'
    | '/passenger'
    | '/billing'
    | '/dashboard'
    | '/drivers'
    | '/games'
    | '/incidents'
    | '/live-ops'
    | '/medicaid-billing'
    | '/medicaid-trips'
    | '/messages'
    | '/news'
    | '/news-feed'
    | '/passengers'
    | '/reports'
    | '/schedules'
    | '/team'
    | '/trips'
    | '/driver/earnings'
    | '/driver/history'
    | '/driver/messages'
    | '/driver/profile'
    | '/driver/signin'
    | '/passenger/apply'
    | '/passenger/games'
    | '/passenger/news'
    | '/track/$tripId'
    | '/driver/'
    | '/passenger/'
    | '/medicaid-trips/new'
    | '/payroll/$driverId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/billing'
    | '/dashboard'
    | '/drivers'
    | '/games'
    | '/incidents'
    | '/live-ops'
    | '/medicaid-billing'
    | '/medicaid-trips'
    | '/messages'
    | '/news'
    | '/news-feed'
    | '/passengers'
    | '/reports'
    | '/schedules'
    | '/team'
    | '/trips'
    | '/driver/earnings'
    | '/driver/history'
    | '/driver/messages'
    | '/driver/profile'
    | '/driver/signin'
    | '/passenger/apply'
    | '/passenger/games'
    | '/passenger/news'
    | '/track/$tripId'
    | '/driver'
    | '/passenger'
    | '/medicaid-trips/new'
    | '/payroll/$driverId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/driver'
    | '/passenger'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/drivers'
    | '/_authenticated/games'
    | '/_authenticated/incidents'
    | '/_authenticated/live-ops'
    | '/_authenticated/medicaid-billing'
    | '/_authenticated/medicaid-trips'
    | '/_authenticated/messages'
    | '/_authenticated/news'
    | '/_authenticated/news-feed'
    | '/_authenticated/passengers'
    | '/_authenticated/reports'
    | '/_authenticated/schedules'
    | '/_authenticated/team'
    | '/_authenticated/trips'
    | '/driver/earnings'
    | '/driver/history'
    | '/driver/messages'
    | '/driver/profile'
    | '/driver/signin'
    | '/passenger/apply'
    | '/passenger/games'
    | '/passenger/news'
    | '/track/$tripId'
    | '/driver/'
    | '/passenger/'
    | '/_authenticated/medicaid-trips/new'
    | '/_authenticated/payroll/$driverId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DriverRoute: typeof DriverRouteWithChildren
  PassengerRoute: typeof PassengerRouteWithChildren
  TrackTripIdRoute: typeof TrackTripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/passenger': {
      id: '/passenger'
      path: '/passenger'
      fullPath: '/passenger'
      preLoaderRoute: typeof PassengerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/': {
      id: '/passenger/'
      path: '/'
      fullPath: '/passenger/'
      preLoaderRoute: typeof PassengerIndexRouteImport
      parentRoute: typeof PassengerRoute
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/track/$tripId': {
      id: '/track/$tripId'
      path: '/track/$tripId'
      fullPath: '/track/$tripId'
      preLoaderRoute: typeof TrackTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/news': {
      id: '/passenger/news'
      path: '/news'
      fullPath: '/passenger/news'
      preLoaderRoute: typeof PassengerNewsRouteImport
      parentRoute: typeof PassengerRoute
    }
    '/passenger/games': {
      id: '/passenger/games'
      path: '/games'
      fullPath: '/passenger/games'
      preLoaderRoute: typeof PassengerGamesRouteImport
      parentRoute: typeof PassengerRoute
    }
    '/passenger/apply': {
      id: '/passenger/apply'
      path: '/apply'
      fullPath: '/passenger/apply'
      preLoaderRoute: typeof PassengerApplyRouteImport
      parentRoute: typeof PassengerRoute
    }
    '/driver/signin': {
      id: '/driver/signin'
      path: '/signin'
      fullPath: '/driver/signin'
      preLoaderRoute: typeof DriverSigninRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/profile': {
      id: '/driver/profile'
      path: '/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/messages': {
      id: '/driver/messages'
      path: '/messages'
      fullPath: '/driver/messages'
      preLoaderRoute: typeof DriverMessagesRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/history': {
      id: '/driver/history'
      path: '/history'
      fullPath: '/driver/history'
      preLoaderRoute: typeof DriverHistoryRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/earnings': {
      id: '/driver/earnings'
      path: '/earnings'
      fullPath: '/driver/earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/_authenticated/trips': {
      id: '/_authenticated/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthenticatedTripsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedules': {
      id: '/_authenticated/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthenticatedSchedulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passengers': {
      id: '/_authenticated/passengers'
      path: '/passengers'
      fullPath: '/passengers'
      preLoaderRoute: typeof AuthenticatedPassengersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news-feed': {
      id: '/_authenticated/news-feed'
      path: '/news-feed'
      fullPath: '/news-feed'
      preLoaderRoute: typeof AuthenticatedNewsFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medicaid-trips': {
      id: '/_authenticated/medicaid-trips'
      path: '/medicaid-trips'
      fullPath: '/medicaid-trips'
      preLoaderRoute: typeof AuthenticatedMedicaidTripsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medicaid-billing': {
      id: '/_authenticated/medicaid-billing'
      path: '/medicaid-billing'
      fullPath: '/medicaid-billing'
      preLoaderRoute: typeof AuthenticatedMedicaidBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-ops': {
      id: '/_authenticated/live-ops'
      path: '/live-ops'
      fullPath: '/live-ops'
      preLoaderRoute: typeof AuthenticatedLiveOpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidents': {
      id: '/_authenticated/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthenticatedIncidentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games': {
      id: '/_authenticated/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AuthenticatedGamesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drivers': {
      id: '/_authenticated/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AuthenticatedDriversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll/$driverId': {
      id: '/_authenticated/payroll/$driverId'
      path: '/payroll/$driverId'
      fullPath: '/payroll/$driverId'
      preLoaderRoute: typeof AuthenticatedPayrollDriverIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medicaid-trips/new': {
      id: '/_authenticated/medicaid-trips/new'
      path: '/new'
      fullPath: '/medicaid-trips/new'
      preLoaderRoute: typeof AuthenticatedMedicaidTripsNewRouteImport
      parentRoute: typeof AuthenticatedMedicaidTripsRoute
    }
  }
}

interface AuthenticatedMedicaidTripsRouteChildren {
  AuthenticatedMedicaidTripsNewRoute: typeof AuthenticatedMedicaidTripsNewRoute
}

const AuthenticatedMedicaidTripsRouteChildren: AuthenticatedMedicaidTripsRouteChildren =
  {
    AuthenticatedMedicaidTripsNewRoute: AuthenticatedMedicaidTripsNewRoute,
  }

const AuthenticatedMedicaidTripsRouteWithChildren =
  AuthenticatedMedicaidTripsRoute._addFileChildren(
    AuthenticatedMedicaidTripsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDriversRoute: typeof AuthenticatedDriversRoute
  AuthenticatedGamesRoute: typeof AuthenticatedGamesRoute
  AuthenticatedIncidentsRoute: typeof AuthenticatedIncidentsRoute
  AuthenticatedLiveOpsRoute: typeof AuthenticatedLiveOpsRoute
  AuthenticatedMedicaidBillingRoute: typeof AuthenticatedMedicaidBillingRoute
  AuthenticatedMedicaidTripsRoute: typeof AuthenticatedMedicaidTripsRouteWithChildren
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRoute
  AuthenticatedNewsFeedRoute: typeof AuthenticatedNewsFeedRoute
  AuthenticatedPassengersRoute: typeof AuthenticatedPassengersRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSchedulesRoute: typeof AuthenticatedSchedulesRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTripsRoute: typeof AuthenticatedTripsRoute
  AuthenticatedPayrollDriverIdRoute: typeof AuthenticatedPayrollDriverIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDriversRoute: AuthenticatedDriversRoute,
  AuthenticatedGamesRoute: AuthenticatedGamesRoute,
  AuthenticatedIncidentsRoute: AuthenticatedIncidentsRoute,
  AuthenticatedLiveOpsRoute: AuthenticatedLiveOpsRoute,
  AuthenticatedMedicaidBillingRoute: AuthenticatedMedicaidBillingRoute,
  AuthenticatedMedicaidTripsRoute: AuthenticatedMedicaidTripsRouteWithChildren,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNewsRoute: AuthenticatedNewsRoute,
  AuthenticatedNewsFeedRoute: AuthenticatedNewsFeedRoute,
  AuthenticatedPassengersRoute: AuthenticatedPassengersRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSchedulesRoute: AuthenticatedSchedulesRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTripsRoute: AuthenticatedTripsRoute,
  AuthenticatedPayrollDriverIdRoute: AuthenticatedPayrollDriverIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DriverRouteChildren {
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverHistoryRoute: typeof DriverHistoryRoute
  DriverMessagesRoute: typeof DriverMessagesRoute
  DriverProfileRoute: typeof DriverProfileRoute
  DriverSigninRoute: typeof DriverSigninRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverEarningsRoute: DriverEarningsRoute,
  DriverHistoryRoute: DriverHistoryRoute,
  DriverMessagesRoute: DriverMessagesRoute,
  DriverProfileRoute: DriverProfileRoute,
  DriverSigninRoute: DriverSigninRoute,
  DriverIndexRoute: DriverIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface PassengerRouteChildren {
  PassengerApplyRoute: typeof PassengerApplyRoute
  PassengerGamesRoute: typeof PassengerGamesRoute
  PassengerNewsRoute: typeof PassengerNewsRoute
  PassengerIndexRoute: typeof PassengerIndexRoute
}

const PassengerRouteChildren: PassengerRouteChildren = {
  PassengerApplyRoute: PassengerApplyRoute,
  PassengerGamesRoute: PassengerGamesRoute,
  PassengerNewsRoute: PassengerNewsRoute,
  PassengerIndexRoute: PassengerIndexRoute,
}

const PassengerRouteWithChildren = PassengerRoute._addFileChildren(
  PassengerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DriverRoute: DriverRouteWithChildren,
  PassengerRoute: PassengerRouteWithChildren,
  TrackTripIdRoute: TrackTripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
