-- =====================================================================
-- RedArt - CURRENT SCHEMA EXPORT (generated, do not edit by hand)
-- Part 3: primary keys, unique, check, then foreign keys
-- Source: live `public` schema, catalog introspection, read-only.
-- Contains no data, no secrets, no cron/net schedules.
-- Execute the parts strictly in filename order (01 -> 10).
-- =====================================================================

-- primary key / unique / check (136)
ALTER TABLE public.admin_notifications ADD CONSTRAINT admin_notifications_pkey PRIMARY KEY (id);
ALTER TABLE public.app_settings ADD CONSTRAINT app_settings_pkey PRIMARY KEY (key);
ALTER TABLE public.auto_pilot_runs ADD CONSTRAINT auto_pilot_runs_pkey PRIMARY KEY (id);
ALTER TABLE public.auto_pilot_runs ADD CONSTRAINT auto_pilot_runs_status_check CHECK ((status = ANY (ARRAY['running'::text, 'stopped'::text, 'finished'::text])));
ALTER TABLE public.billing_audit_log ADD CONSTRAINT billing_audit_log_actor_type_check CHECK ((actor_type = ANY (ARRAY['admin'::text, 'driver'::text, 'system'::text])));
ALTER TABLE public.billing_audit_log ADD CONSTRAINT billing_audit_log_pkey PRIMARY KEY (id);
ALTER TABLE public.billing_rate_settings ADD CONSTRAINT billing_rate_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.billing_rate_settings ADD CONSTRAINT billing_rate_settings_provider_vehicle_unit_key UNIQUE (provider_id, vehicle_type, unit_type);
ALTER TABLE public.billing_rate_settings ADD CONSTRAINT billing_rate_settings_unit_type_check CHECK ((unit_type = ANY (ARRAY['trip'::text, 'mile'::text])));
ALTER TABLE public.billing_rate_settings ADD CONSTRAINT billing_rate_settings_vehicle_type_check CHECK ((vehicle_type = ANY (ARRAY['ambulatory'::text, 'wheelchair_van'::text])));
ALTER TABLE public.billing_records ADD CONSTRAINT billing_records_pkey PRIMARY KEY (id);
ALTER TABLE public.billing_records ADD CONSTRAINT billing_records_status_check CHECK ((status = ANY (ARRAY['pending_review'::text, 'pending_submit'::text, 'queued'::text, 'submitting'::text, 'submitted'::text, 'approved'::text, 'rejected'::text, 'needs_fix'::text, 'paid'::text, 'suspended'::text, 'denied'::text])));
ALTER TABLE public.billing_records ADD CONSTRAINT billing_records_trip_id_key1 UNIQUE (trip_id);
ALTER TABLE public.billing_settings ADD CONSTRAINT billing_settings_company_id_key UNIQUE (company_id);
ALTER TABLE public.billing_settings ADD CONSTRAINT billing_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.chat_conversations ADD CONSTRAINT chat_conversations_kind_check CHECK ((kind = ANY (ARRAY['driver_admin'::text, 'passenger_admin'::text, 'driver_passenger'::text])));
ALTER TABLE public.chat_conversations ADD CONSTRAINT chat_conversations_pkey PRIMARY KEY (id);
ALTER TABLE public.chat_messages ADD CONSTRAINT chat_messages_body_check CHECK (((length(body) >= 1) AND (length(body) <= 4000)));
ALTER TABLE public.chat_messages ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);
ALTER TABLE public.claim_modifier_audit ADD CONSTRAINT claim_modifier_audit_action_check CHECK ((action = ANY (ARRAY['added'::text, 'removed'::text])));
ALTER TABLE public.claim_modifier_audit ADD CONSTRAINT claim_modifier_audit_pkey PRIMARY KEY (id);
ALTER TABLE public.claim_resubmissions ADD CONSTRAINT claim_resubmissions_pkey PRIMARY KEY (id);
ALTER TABLE public.claim_resubmissions ADD CONSTRAINT claim_resubmissions_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'queued'::text, 'submitted'::text, 'paid'::text, 'denied'::text, 'cancelled'::text])));
ALTER TABLE public.claim_service_lines ADD CONSTRAINT claim_service_lines_pkey PRIMARY KEY (id);
ALTER TABLE public.claim_status_sync_state ADD CONSTRAINT claim_status_sync_state_pkey PRIMARY KEY (id);
ALTER TABLE public.claim_status_sync_state ADD CONSTRAINT claim_status_sync_state_singleton_check CHECK (singleton);
ALTER TABLE public.companies ADD CONSTRAINT companies_pkey PRIMARY KEY (id);
ALTER TABLE public.companies ADD CONSTRAINT companies_status_check CHECK ((status = ANY (ARRAY['active'::text, 'suspended'::text])));
ALTER TABLE public.companies ADD CONSTRAINT companies_url_slug_key UNIQUE (url_slug);
ALTER TABLE public.company_comm_settings ADD CONSTRAINT company_comm_settings_pkey PRIMARY KEY (company_id);
ALTER TABLE public.company_comm_settings ADD CONSTRAINT company_comm_settings_provider_check CHECK ((provider = ANY (ARRAY['telnyx'::text, 'twilio'::text, 'none'::text])));
ALTER TABLE public.company_pay_settings ADD CONSTRAINT company_pay_settings_commission_base_check CHECK ((commission_base = ANY (ARRAY['unset'::text, 'paid_claims'::text, 'submitted_claims'::text, 'estimated_fares'::text])));
ALTER TABLE public.company_pay_settings ADD CONSTRAINT company_pay_settings_commission_percentage_check CHECK (((commission_percentage IS NULL) OR ((commission_percentage >= (0)::numeric) AND (commission_percentage <= (100)::numeric))));
ALTER TABLE public.company_pay_settings ADD CONSTRAINT company_pay_settings_default_plan_check CHECK ((default_plan = ANY (ARRAY['hourly'::text, 'commission'::text, 'per_trip'::text, 'hybrid_hourly_commission'::text, 'hybrid_hourly_per_trip'::text])));
ALTER TABLE public.company_pay_settings ADD CONSTRAINT company_pay_settings_hourly_rate_check CHECK (((hourly_rate IS NULL) OR (hourly_rate >= (0)::numeric)));
ALTER TABLE public.company_pay_settings ADD CONSTRAINT company_pay_settings_per_trip_amount_check CHECK (((per_trip_amount IS NULL) OR (per_trip_amount >= (0)::numeric)));
ALTER TABLE public.company_pay_settings ADD CONSTRAINT company_pay_settings_per_trip_source_check CHECK ((per_trip_source = 'completed_trips'::text));
ALTER TABLE public.company_pay_settings ADD CONSTRAINT company_pay_settings_pkey PRIMARY KEY (company_id);
ALTER TABLE public.company_subscriptions ADD CONSTRAINT company_subscriptions_company_id_key UNIQUE (company_id);
ALTER TABLE public.company_subscriptions ADD CONSTRAINT company_subscriptions_pkey PRIMARY KEY (id);
ALTER TABLE public.contest_entries ADD CONSTRAINT contest_entries_passenger_id_period_start_key UNIQUE (passenger_id, period_start);
ALTER TABLE public.contest_entries ADD CONSTRAINT contest_entries_pkey PRIMARY KEY (id);
ALTER TABLE public.contest_winners ADD CONSTRAINT contest_winners_pkey PRIMARY KEY (id);
ALTER TABLE public.destination_place_cache ADD CONSTRAINT destination_place_cache_pkey PRIMARY KEY (id);
ALTER TABLE public.destination_review_overrides ADD CONSTRAINT destination_review_overrides_pkey PRIMARY KEY (id);
ALTER TABLE public.dispatch_events ADD CONSTRAINT dispatch_events_pkey PRIMARY KEY (id);
ALTER TABLE public.dispatch_trip_report_drafts ADD CONSTRAINT dispatch_trip_report_drafts_dispatch_trip_id_key UNIQUE (dispatch_trip_id);
ALTER TABLE public.dispatch_trip_report_drafts ADD CONSTRAINT dispatch_trip_report_drafts_pkey PRIMARY KEY (id);
ALTER TABLE public.driver_claim_payout_items ADD CONSTRAINT driver_claim_payout_items_pkey PRIMARY KEY (id);
ALTER TABLE public.driver_claim_payout_items ADD CONSTRAINT driver_claim_payout_items_trip_once UNIQUE (trip_id);
ALTER TABLE public.driver_claim_payouts ADD CONSTRAINT driver_claim_payouts_pkey PRIMARY KEY (id);
ALTER TABLE public.driver_hour_clearings ADD CONSTRAINT driver_hour_clearings_pkey PRIMARY KEY (id);
ALTER TABLE public.driver_insurance_docs ADD CONSTRAINT driver_insurance_docs_pkey PRIMARY KEY (id);
ALTER TABLE public.driver_insurance_docs ADD CONSTRAINT driver_insurance_docs_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'verified'::text, 'rejected'::text])));
ALTER TABLE public.driver_pay ADD CONSTRAINT driver_pay_pkey PRIMARY KEY (driver_id);
ALTER TABLE public.driver_pay_plans ADD CONSTRAINT driver_pay_plans_commission_base_check CHECK (((commission_base IS NULL) OR (commission_base = ANY (ARRAY['paid_claims'::text, 'submitted_claims'::text, 'estimated_fares'::text]))));
ALTER TABLE public.driver_pay_plans ADD CONSTRAINT driver_pay_plans_commission_percentage_check CHECK (((commission_percentage IS NULL) OR ((commission_percentage >= (0)::numeric) AND (commission_percentage <= (100)::numeric))));
ALTER TABLE public.driver_pay_plans ADD CONSTRAINT driver_pay_plans_hourly_rate_check CHECK (((hourly_rate IS NULL) OR (hourly_rate >= (0)::numeric)));
ALTER TABLE public.driver_pay_plans ADD CONSTRAINT driver_pay_plans_per_trip_amount_check CHECK (((per_trip_amount IS NULL) OR (per_trip_amount >= (0)::numeric)));
ALTER TABLE public.driver_pay_plans ADD CONSTRAINT driver_pay_plans_per_trip_source_check CHECK (((per_trip_source IS NULL) OR (per_trip_source = 'completed_trips'::text)));
ALTER TABLE public.driver_pay_plans ADD CONSTRAINT driver_pay_plans_pkey PRIMARY KEY (driver_id);
ALTER TABLE public.driver_pay_plans ADD CONSTRAINT driver_pay_plans_plan_check CHECK (((plan IS NULL) OR (plan = ANY (ARRAY['hourly'::text, 'commission'::text, 'per_trip'::text, 'hybrid_hourly_commission'::text, 'hybrid_hourly_per_trip'::text]))));
ALTER TABLE public.driver_payout_items ADD CONSTRAINT driver_payout_items_kind_check CHECK ((kind = ANY (ARRAY['shift'::text, 'trip'::text, 'claim'::text, 'fuel'::text])));
ALTER TABLE public.driver_payout_items ADD CONSTRAINT driver_payout_items_pkey PRIMARY KEY (id);
ALTER TABLE public.driver_payouts ADD CONSTRAINT driver_payouts_pkey PRIMARY KEY (id);
ALTER TABLE public.driver_shifts ADD CONSTRAINT driver_shifts_pkey PRIMARY KEY (id);
ALTER TABLE public.driver_trip_drafts ADD CONSTRAINT driver_trip_drafts_pkey PRIMARY KEY (id);
ALTER TABLE public.drivers ADD CONSTRAINT drivers_pkey PRIMARY KEY (id);
ALTER TABLE public.drivers ADD CONSTRAINT drivers_user_id_key UNIQUE (user_id);
ALTER TABLE public.events ADD CONSTRAINT events_pkey PRIMARY KEY (id);
ALTER TABLE public.fuel_logs ADD CONSTRAINT fuel_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.games ADD CONSTRAINT games_pkey PRIMARY KEY (id);
ALTER TABLE public.gas_receipts ADD CONSTRAINT gas_receipts_pkey PRIMARY KEY (id);
ALTER TABLE public.incidents ADD CONSTRAINT incidents_pkey PRIMARY KEY (id);
ALTER TABLE public.inspections ADD CONSTRAINT inspections_driver_id_inspection_date_key UNIQUE (driver_id, inspection_date);
ALTER TABLE public.inspections ADD CONSTRAINT inspections_pkey PRIMARY KEY (id);
ALTER TABLE public.manual_claim_records ADD CONSTRAINT manual_claim_records_pkey PRIMARY KEY (id);
ALTER TABLE public.medicaid_trip_legs ADD CONSTRAINT medicaid_trip_legs_leg_index_check CHECK ((leg_index = ANY (ARRAY[1, 2])));
ALTER TABLE public.medicaid_trip_legs ADD CONSTRAINT medicaid_trip_legs_medicaid_trip_id_leg_index_key UNIQUE (medicaid_trip_id, leg_index);
ALTER TABLE public.medicaid_trip_legs ADD CONSTRAINT medicaid_trip_legs_pkey PRIMARY KEY (id);
ALTER TABLE public.medicaid_trips ADD CONSTRAINT medicaid_trips_pkey PRIMARY KEY (id);
ALTER TABLE public.messages ADD CONSTRAINT messages_pkey PRIMARY KEY (id);
ALTER TABLE public.news_items ADD CONSTRAINT news_items_pkey PRIMARY KEY (id);
ALTER TABLE public.passengers ADD CONSTRAINT passengers_identifier_check CHECK (((medicaid_id IS NOT NULL) OR ((ssn_last4 IS NOT NULL) AND (date_of_birth IS NOT NULL)) OR (device_id IS NOT NULL)));
ALTER TABLE public.passengers ADD CONSTRAINT passengers_pkey PRIMARY KEY (id);
ALTER TABLE public.payroll_audit_log ADD CONSTRAINT payroll_audit_log_pkey PRIMARY KEY (id);
ALTER TABLE public.payroll_items ADD CONSTRAINT payroll_items_kind_check CHECK ((kind = ANY (ARRAY['claim'::text, 'manual'::text, 'adjustment'::text])));
ALTER TABLE public.payroll_items ADD CONSTRAINT payroll_items_payroll_status_check CHECK ((payroll_status = ANY (ARRAY['not_added'::text, 'added'::text, 'paid'::text])));
ALTER TABLE public.payroll_items ADD CONSTRAINT payroll_items_pkey PRIMARY KEY (id);
ALTER TABLE public.pricing_config ADD CONSTRAINT pricing_config_pkey PRIMARY KEY (id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.push_subscriptions ADD CONSTRAINT push_subscriptions_endpoint_key UNIQUE (endpoint);
ALTER TABLE public.push_subscriptions ADD CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id);
ALTER TABLE public.rewards_settings ADD CONSTRAINT rewards_settings_id_check CHECK ((id = true));
ALTER TABLE public.rewards_settings ADD CONSTRAINT rewards_settings_period_type_check CHECK ((period_type = ANY (ARRAY['weekly'::text, 'monthly'::text])));
ALTER TABLE public.rewards_settings ADD CONSTRAINT rewards_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.rewards_settings ADD CONSTRAINT rewards_settings_rides_required_check CHECK ((rides_required > 0));
ALTER TABLE public.rewards_settings ADD CONSTRAINT rewards_settings_winners_per_period_check CHECK ((winners_per_period > 0));
ALTER TABLE public.ride_passengers ADD CONSTRAINT ride_passengers_pkey PRIMARY KEY (id);
ALTER TABLE public.ride_requests ADD CONSTRAINT ride_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.ride_requests ADD CONSTRAINT ride_requests_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text, 'cancelled'::text, 'expired'::text])));
ALTER TABLE public.riders ADD CONSTRAINT riders_last_4_ssn_check CHECK (((last_4_ssn IS NULL) OR (last_4_ssn ~ '^[0-9]{4}$'::text)));
ALTER TABLE public.riders ADD CONSTRAINT riders_medicaid_id_key UNIQUE (medicaid_id);
ALTER TABLE public.riders ADD CONSTRAINT riders_pkey PRIMARY KEY (id);
ALTER TABLE public.robot_api_keys ADD CONSTRAINT robot_api_keys_api_key_key UNIQUE (api_key);
ALTER TABLE public.robot_api_keys ADD CONSTRAINT robot_api_keys_pkey PRIMARY KEY (id);
ALTER TABLE public.robot_workers ADD CONSTRAINT robot_workers_pkey PRIMARY KEY (id);
ALTER TABLE public.route_stops ADD CONSTRAINT route_stops_pkey PRIMARY KEY (id);
ALTER TABLE public.routes ADD CONSTRAINT routes_pkey PRIMARY KEY (id);
ALTER TABLE public.saved_places ADD CONSTRAINT saved_places_kind_check CHECK ((kind = ANY (ARRAY['home'::text, 'work'::text, 'custom'::text])));
ALTER TABLE public.saved_places ADD CONSTRAINT saved_places_pkey PRIMARY KEY (id);
ALTER TABLE public.shifts ADD CONSTRAINT shifts_pkey PRIMARY KEY (id);
ALTER TABLE public.sms_conversations ADD CONSTRAINT sms_conversations_pkey PRIMARY KEY (id);
ALTER TABLE public.sms_conversations ADD CONSTRAINT sms_conversations_status_check CHECK ((status = ANY (ARRAY['needs_review'::text, 'open'::text, 'closed'::text])));
ALTER TABLE public.sms_messages ADD CONSTRAINT sms_messages_direction_check CHECK ((direction = ANY (ARRAY['inbound'::text, 'outbound'::text])));
ALTER TABLE public.sms_messages ADD CONSTRAINT sms_messages_pkey PRIMARY KEY (id);
ALTER TABLE public.sms_messages ADD CONSTRAINT sms_messages_status_check CHECK ((status = ANY (ARRAY['queued'::text, 'sending'::text, 'sent'::text, 'delivered'::text, 'failed'::text, 'received'::text, 'skipped'::text])));
ALTER TABLE public.staff_conversations ADD CONSTRAINT staff_conversations_distinct_members CHECK ((member_a <> member_b));
ALTER TABLE public.staff_conversations ADD CONSTRAINT staff_conversations_pkey PRIMARY KEY (id);
ALTER TABLE public.staff_messages ADD CONSTRAINT staff_messages_pkey PRIMARY KEY (id);
ALTER TABLE public.state_portal_credentials ADD CONSTRAINT state_portal_credentials_pkey PRIMARY KEY (id);
ALTER TABLE public.submission_batches ADD CONSTRAINT submission_batches_pkey PRIMARY KEY (id);
ALTER TABLE public.submission_queue_state ADD CONSTRAINT submission_queue_state_id_check CHECK (id);
ALTER TABLE public.submission_queue_state ADD CONSTRAINT submission_queue_state_pkey PRIMARY KEY (id);
ALTER TABLE public.subscription_payments ADD CONSTRAINT subscription_payments_pkey PRIMARY KEY (id);
ALTER TABLE public.trip_billing_records ADD CONSTRAINT billing_records_trip_id_key UNIQUE (trip_id);
ALTER TABLE public.trip_billing_records ADD CONSTRAINT trip_billing_records_pkey PRIMARY KEY (id);
ALTER TABLE public.trip_destination_classifications ADD CONSTRAINT trip_destination_classifications_pkey PRIMARY KEY (id);
ALTER TABLE public.trip_media ADD CONSTRAINT trip_media_pkey PRIMARY KEY (id);
ALTER TABLE public.trip_stops ADD CONSTRAINT trip_stops_pkey PRIMARY KEY (id);
ALTER TABLE public.trips ADD CONSTRAINT trips_passenger_rating_check CHECK (((passenger_rating >= 1) AND (passenger_rating <= 5)));
ALTER TABLE public.trips ADD CONSTRAINT trips_pkey PRIMARY KEY (id);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_role_key UNIQUE (user_id, role);
ALTER TABLE public.vehicle_expenses ADD CONSTRAINT vehicle_expenses_category_check CHECK ((category = ANY (ARRAY['oil_change'::text, 'tires'::text, 'repair'::text, 'inspection'::text, 'maintenance'::text, 'car_wash'::text, 'fuel'::text, 'other'::text])));
ALTER TABLE public.vehicle_expenses ADD CONSTRAINT vehicle_expenses_pkey PRIMARY KEY (id);

-- foreign key (122)
ALTER TABLE public.auto_pilot_runs ADD CONSTRAINT auto_pilot_runs_started_by_fkey FOREIGN KEY (started_by) REFERENCES auth.users(id);
ALTER TABLE public.billing_audit_log ADD CONSTRAINT billing_audit_log_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.billing_audit_log ADD CONSTRAINT billing_audit_log_billing_record_id_fkey FOREIGN KEY (billing_record_id) REFERENCES billing_records(id) ON DELETE CASCADE;
ALTER TABLE public.billing_rate_settings ADD CONSTRAINT billing_rate_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.billing_rate_settings ADD CONSTRAINT billing_rate_settings_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.billing_records ADD CONSTRAINT billing_records_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.billing_records ADD CONSTRAINT billing_records_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.billing_records ADD CONSTRAINT billing_records_trip_id_fkey1 FOREIGN KEY (trip_id) REFERENCES medicaid_trips(id) ON DELETE CASCADE;
ALTER TABLE public.chat_conversations ADD CONSTRAINT chat_conversations_driver_user_id_fkey FOREIGN KEY (driver_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.chat_conversations ADD CONSTRAINT chat_conversations_passenger_user_id_fkey FOREIGN KEY (passenger_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.chat_conversations ADD CONSTRAINT chat_conversations_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE SET NULL;
ALTER TABLE public.chat_messages ADD CONSTRAINT chat_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES chat_conversations(id) ON DELETE CASCADE;
ALTER TABLE public.chat_messages ADD CONSTRAINT chat_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.claim_modifier_audit ADD CONSTRAINT claim_modifier_audit_resubmission_id_fkey FOREIGN KEY (resubmission_id) REFERENCES claim_resubmissions(id) ON DELETE CASCADE;
ALTER TABLE public.claim_modifier_audit ADD CONSTRAINT claim_modifier_audit_service_line_id_fkey FOREIGN KEY (service_line_id) REFERENCES claim_service_lines(id) ON DELETE CASCADE;
ALTER TABLE public.claim_resubmissions ADD CONSTRAINT claim_resubmissions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.claim_resubmissions ADD CONSTRAINT claim_resubmissions_original_trip_id_fkey FOREIGN KEY (original_trip_id) REFERENCES medicaid_trips(id) ON DELETE CASCADE;
ALTER TABLE public.claim_service_lines ADD CONSTRAINT claim_service_lines_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.claim_service_lines ADD CONSTRAINT claim_service_lines_resubmission_id_fkey FOREIGN KEY (resubmission_id) REFERENCES claim_resubmissions(id) ON DELETE CASCADE;
ALTER TABLE public.claim_service_lines ADD CONSTRAINT claim_service_lines_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES medicaid_trips(id) ON DELETE SET NULL;
ALTER TABLE public.company_comm_settings ADD CONSTRAINT company_comm_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.company_pay_settings ADD CONSTRAINT company_pay_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.company_subscriptions ADD CONSTRAINT company_subscriptions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.contest_entries ADD CONSTRAINT contest_entries_passenger_id_fkey FOREIGN KEY (passenger_id) REFERENCES passengers(id) ON DELETE CASCADE;
ALTER TABLE public.contest_winners ADD CONSTRAINT contest_winners_passenger_id_fkey FOREIGN KEY (passenger_id) REFERENCES passengers(id) ON DELETE CASCADE;
ALTER TABLE public.destination_place_cache ADD CONSTRAINT destination_place_cache_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.destination_review_overrides ADD CONSTRAINT destination_review_overrides_billing_record_id_fkey FOREIGN KEY (billing_record_id) REFERENCES billing_records(id) ON DELETE CASCADE;
ALTER TABLE public.destination_review_overrides ADD CONSTRAINT destination_review_overrides_classification_id_fkey FOREIGN KEY (classification_id) REFERENCES trip_destination_classifications(id) ON DELETE SET NULL;
ALTER TABLE public.destination_review_overrides ADD CONSTRAINT destination_review_overrides_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.destination_review_overrides ADD CONSTRAINT destination_review_overrides_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES medicaid_trips(id) ON DELETE CASCADE;
ALTER TABLE public.dispatch_trip_report_drafts ADD CONSTRAINT dispatch_trip_report_drafts_dispatch_trip_id_fkey FOREIGN KEY (dispatch_trip_id) REFERENCES trips(id) ON DELETE CASCADE;
ALTER TABLE public.driver_claim_payout_items ADD CONSTRAINT driver_claim_payout_items_payout_id_fkey FOREIGN KEY (payout_id) REFERENCES driver_claim_payouts(id) ON DELETE CASCADE;
ALTER TABLE public.driver_claim_payout_items ADD CONSTRAINT driver_claim_payout_items_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES medicaid_trips(id) ON DELETE CASCADE;
ALTER TABLE public.driver_claim_payouts ADD CONSTRAINT driver_claim_payouts_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);
ALTER TABLE public.driver_claim_payouts ADD CONSTRAINT driver_claim_payouts_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE;
ALTER TABLE public.driver_hour_clearings ADD CONSTRAINT driver_hour_clearings_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);
ALTER TABLE public.driver_hour_clearings ADD CONSTRAINT driver_hour_clearings_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE;
ALTER TABLE public.driver_insurance_docs ADD CONSTRAINT driver_insurance_docs_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.driver_insurance_docs ADD CONSTRAINT driver_insurance_docs_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE;
ALTER TABLE public.driver_pay ADD CONSTRAINT driver_pay_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);
ALTER TABLE public.driver_pay ADD CONSTRAINT driver_pay_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE;
ALTER TABLE public.driver_pay_plans ADD CONSTRAINT driver_pay_plans_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);
ALTER TABLE public.driver_pay_plans ADD CONSTRAINT driver_pay_plans_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE;
ALTER TABLE public.driver_payout_items ADD CONSTRAINT driver_payout_items_payout_id_fkey FOREIGN KEY (payout_id) REFERENCES driver_payouts(id) ON DELETE CASCADE;
ALTER TABLE public.driver_payouts ADD CONSTRAINT driver_payouts_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);
ALTER TABLE public.driver_payouts ADD CONSTRAINT driver_payouts_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE;
ALTER TABLE public.driver_shifts ADD CONSTRAINT driver_shifts_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.driver_shifts ADD CONSTRAINT driver_shifts_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE;
ALTER TABLE public.driver_shifts ADD CONSTRAINT driver_shifts_payout_id_fkey FOREIGN KEY (payout_id) REFERENCES driver_payouts(id) ON DELETE SET NULL;
ALTER TABLE public.driver_trip_drafts ADD CONSTRAINT driver_trip_drafts_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.drivers ADD CONSTRAINT drivers_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.drivers ADD CONSTRAINT drivers_merged_into_fkey FOREIGN KEY (merged_into) REFERENCES drivers(id) ON DELETE SET NULL;
ALTER TABLE public.drivers ADD CONSTRAINT drivers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_logs ADD CONSTRAINT fuel_logs_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE;
ALTER TABLE public.gas_receipts ADD CONSTRAINT gas_receipts_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.gas_receipts ADD CONSTRAINT gas_receipts_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE;
ALTER TABLE public.gas_receipts ADD CONSTRAINT gas_receipts_payout_id_fkey FOREIGN KEY (payout_id) REFERENCES driver_payouts(id) ON DELETE SET NULL;
ALTER TABLE public.gas_receipts ADD CONSTRAINT gas_receipts_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES driver_shifts(id) ON DELETE SET NULL;
ALTER TABLE public.incidents ADD CONSTRAINT incidents_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE;
ALTER TABLE public.incidents ADD CONSTRAINT incidents_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE SET NULL;
ALTER TABLE public.inspections ADD CONSTRAINT inspections_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE;
ALTER TABLE public.manual_claim_records ADD CONSTRAINT manual_claim_records_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.manual_claim_records ADD CONSTRAINT manual_claim_records_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE;
ALTER TABLE public.medicaid_trip_legs ADD CONSTRAINT medicaid_trip_legs_medicaid_trip_id_fkey FOREIGN KEY (medicaid_trip_id) REFERENCES medicaid_trips(id) ON DELETE CASCADE;
ALTER TABLE public.medicaid_trips ADD CONSTRAINT medicaid_trips_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.medicaid_trips ADD CONSTRAINT medicaid_trips_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES auth.users(id) ON DELETE RESTRICT;
ALTER TABLE public.medicaid_trips ADD CONSTRAINT medicaid_trips_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.medicaid_trips ADD CONSTRAINT medicaid_trips_rider_id_fkey FOREIGN KEY (rider_id) REFERENCES riders(id) ON DELETE RESTRICT;
ALTER TABLE public.medicaid_trips ADD CONSTRAINT medicaid_trips_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.messages ADD CONSTRAINT messages_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE;
ALTER TABLE public.messages ADD CONSTRAINT messages_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.messages ADD CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.passengers ADD CONSTRAINT passengers_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.passengers ADD CONSTRAINT passengers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.payroll_audit_log ADD CONSTRAINT payroll_audit_log_payroll_item_id_fkey FOREIGN KEY (payroll_item_id) REFERENCES payroll_items(id) ON DELETE CASCADE;
ALTER TABLE public.payroll_items ADD CONSTRAINT payroll_items_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.payroll_items ADD CONSTRAINT payroll_items_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE;
ALTER TABLE public.payroll_items ADD CONSTRAINT payroll_items_payout_id_fkey FOREIGN KEY (payout_id) REFERENCES driver_payouts(id) ON DELETE SET NULL;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.push_subscriptions ADD CONSTRAINT push_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.ride_passengers ADD CONSTRAINT ride_passengers_request_id_fkey FOREIGN KEY (request_id) REFERENCES ride_requests(id) ON DELETE CASCADE;
ALTER TABLE public.ride_passengers ADD CONSTRAINT ride_passengers_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE;
ALTER TABLE public.ride_requests ADD CONSTRAINT ride_requests_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.ride_requests ADD CONSTRAINT ride_requests_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE SET NULL;
ALTER TABLE public.ride_requests ADD CONSTRAINT ride_requests_passenger_id_fkey FOREIGN KEY (passenger_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.ride_requests ADD CONSTRAINT ride_requests_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE SET NULL;
ALTER TABLE public.riders ADD CONSTRAINT riders_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.riders ADD CONSTRAINT riders_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.robot_api_keys ADD CONSTRAINT robot_api_keys_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.route_stops ADD CONSTRAINT route_stops_request_id_fkey FOREIGN KEY (request_id) REFERENCES ride_requests(id) ON DELETE SET NULL;
ALTER TABLE public.route_stops ADD CONSTRAINT route_stops_route_id_fkey FOREIGN KEY (route_id) REFERENCES routes(id) ON DELETE CASCADE;
ALTER TABLE public.routes ADD CONSTRAINT routes_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.routes ADD CONSTRAINT routes_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE SET NULL;
ALTER TABLE public.saved_places ADD CONSTRAINT saved_places_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.shifts ADD CONSTRAINT shifts_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE;
ALTER TABLE public.sms_conversations ADD CONSTRAINT sms_conversations_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.sms_conversations ADD CONSTRAINT sms_conversations_passenger_id_fkey FOREIGN KEY (passenger_id) REFERENCES passengers(id) ON DELETE SET NULL;
ALTER TABLE public.sms_messages ADD CONSTRAINT sms_messages_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.sms_messages ADD CONSTRAINT sms_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES sms_conversations(id) ON DELETE CASCADE;
ALTER TABLE public.sms_messages ADD CONSTRAINT sms_messages_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.staff_conversations ADD CONSTRAINT staff_conversations_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.staff_conversations ADD CONSTRAINT staff_conversations_member_a_fkey FOREIGN KEY (member_a) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.staff_conversations ADD CONSTRAINT staff_conversations_member_b_fkey FOREIGN KEY (member_b) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.staff_messages ADD CONSTRAINT staff_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES staff_conversations(id) ON DELETE CASCADE;
ALTER TABLE public.staff_messages ADD CONSTRAINT staff_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.submission_batches ADD CONSTRAINT submission_batches_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.submission_batches ADD CONSTRAINT submission_batches_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.subscription_payments ADD CONSTRAINT subscription_payments_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.trip_billing_records ADD CONSTRAINT billing_records_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE;
ALTER TABLE public.trip_destination_classifications ADD CONSTRAINT trip_destination_classifications_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.trip_destination_classifications ADD CONSTRAINT trip_destination_classifications_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES medicaid_trips(id) ON DELETE CASCADE;
ALTER TABLE public.trip_media ADD CONSTRAINT trip_media_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE;
ALTER TABLE public.trip_stops ADD CONSTRAINT trip_stops_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE;
ALTER TABLE public.trips ADD CONSTRAINT trips_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.trips ADD CONSTRAINT trips_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE SET NULL;
ALTER TABLE public.trips ADD CONSTRAINT trips_passenger_id_fkey FOREIGN KEY (passenger_id) REFERENCES passengers(id) ON DELETE RESTRICT;
ALTER TABLE public.trips ADD CONSTRAINT trips_payout_id_fkey FOREIGN KEY (payout_id) REFERENCES driver_payouts(id) ON DELETE SET NULL;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.vehicle_expenses ADD CONSTRAINT vehicle_expenses_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE public.vehicle_expenses ADD CONSTRAINT vehicle_expenses_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE;
