-- =====================================================================
-- RedArt - CURRENT SCHEMA EXPORT (generated, do not edit by hand)
-- Part 4: non-constraint indexes
-- Source: live `public` schema, catalog introspection, read-only.
-- Contains no data, no secrets, no cron/net schedules.
-- Execute the parts strictly in filename order (01 -> 10).
-- =====================================================================

CREATE INDEX auto_pilot_runs_company_idx ON public.auto_pilot_runs USING btree (company_id, created_at DESC);
CREATE UNIQUE INDEX auto_pilot_runs_one_active ON public.auto_pilot_runs USING btree (company_id) WHERE (status = 'running'::text);
CREATE INDEX billing_audit_log_record_idx ON public.billing_audit_log USING btree (billing_record_id, created_at DESC);
CREATE UNIQUE INDEX billing_rate_settings_company_vehicle_unit_key ON public.billing_rate_settings USING btree (company_id, vehicle_type, unit_type) WHERE (company_id IS NOT NULL);
CREATE UNIQUE INDEX billing_rate_settings_company_vehicle_unit_proc_key ON public.billing_rate_settings USING btree (company_id, vehicle_type, unit_type, procedure_code) WHERE (company_id IS NOT NULL);
CREATE UNIQUE INDEX billing_rate_settings_nocompany_vehicle_unit_key ON public.billing_rate_settings USING btree (vehicle_type, unit_type) WHERE (company_id IS NULL);
CREATE INDEX billing_records_status_check_due_idx ON public.billing_records USING btree (status_check_next_at) WHERE (status_check_next_at IS NOT NULL);
CREATE INDEX billing_records_status_check_idx ON public.billing_records USING btree (status_checked_at NULLS FIRST) WHERE (state_confirmation_number IS NOT NULL);
CREATE INDEX billing_records_status_check_lease_idx ON public.billing_records USING btree (company_id, status_check_next_at) WHERE (status_check_next_at IS NOT NULL);
CREATE INDEX billing_records_status_check_lock_idx ON public.billing_records USING btree (status_check_next_at) WHERE (status_check_next_at IS NOT NULL);
CREATE INDEX billing_records_status_idx ON public.billing_records USING btree (status, updated_at DESC);
CREATE INDEX billing_records_submit_account_key_idx ON public.billing_records USING btree (submit_account_key, status);
CREATE INDEX billing_records_submit_batch_idx ON public.billing_records USING btree (submit_batch_id);
CREATE UNIQUE INDEX billing_records_submit_idem_key ON public.billing_records USING btree (submit_idempotency_key) WHERE (submit_idempotency_key IS NOT NULL);
CREATE INDEX billing_records_submit_queue_idx ON public.billing_records USING btree (status, submit_next_attempt_at, submit_locked_until);
CREATE INDEX billing_records_trip_idx ON public.billing_records USING btree (trip_id);
CREATE INDEX idx_billing_records_attention_archived ON public.billing_records USING btree (attention_archived_at) WHERE (attention_archived_at IS NOT NULL);
CREATE INDEX idx_billing_records_wave_hold ON public.billing_records USING btree (submit_batch_id) WHERE submit_wave_hold;
CREATE UNIQUE INDEX billing_settings_company_uniq ON public.billing_settings USING btree (company_id) NULLS NOT DISTINCT;
CREATE UNIQUE INDEX chat_conversations_driver_admin_uniq ON public.chat_conversations USING btree (driver_user_id) WHERE (kind = 'driver_admin'::text);
CREATE UNIQUE INDEX chat_conversations_passenger_admin_uniq ON public.chat_conversations USING btree (passenger_user_id) WHERE (kind = 'passenger_admin'::text);
CREATE UNIQUE INDEX chat_conversations_trip_uniq ON public.chat_conversations USING btree (trip_id) WHERE ((kind = 'driver_passenger'::text) AND (trip_id IS NOT NULL));
CREATE INDEX chat_messages_conv_created_idx ON public.chat_messages USING btree (conversation_id, created_at);
CREATE INDEX claim_modifier_audit_line_idx ON public.claim_modifier_audit USING btree (service_line_id, created_at DESC);
CREATE INDEX claim_resubmissions_company_idx ON public.claim_resubmissions USING btree (company_id, created_at DESC);
CREATE UNIQUE INDEX claim_resubmissions_one_live ON public.claim_resubmissions USING btree (original_trip_id) WHERE (status = ANY (ARRAY['draft'::text, 'queued'::text]));
CREATE UNIQUE INDEX claim_service_lines_unique ON public.claim_service_lines USING btree (resubmission_id, line_index);
CREATE UNIQUE INDEX companies_twilio_phone_key ON public.companies USING btree (twilio_phone) WHERE (twilio_phone IS NOT NULL);
CREATE INDEX idx_contest_entries_period ON public.contest_entries USING btree (period_start, period_end);
CREATE INDEX idx_contest_winners_period ON public.contest_winners USING btree (period_start);
CREATE UNIQUE INDEX destination_place_cache_company_key ON public.destination_place_cache USING btree (company_id, normalized_key);
CREATE INDEX destination_review_overrides_company_idx ON public.destination_review_overrides USING btree (company_id, created_at DESC);
CREATE INDEX destination_review_overrides_trip_idx ON public.destination_review_overrides USING btree (trip_id);
CREATE INDEX dispatch_events_created_idx ON public.dispatch_events USING btree (created_at DESC);
CREATE INDEX driver_claim_payout_items_payout_idx ON public.driver_claim_payout_items USING btree (payout_id);
CREATE INDEX driver_claim_payouts_driver_idx ON public.driver_claim_payouts USING btree (driver_id, period_start, period_end);
CREATE INDEX idx_driver_hour_clearings_driver ON public.driver_hour_clearings USING btree (driver_id, cleared_at DESC);
CREATE INDEX driver_insurance_docs_driver_idx ON public.driver_insurance_docs USING btree (company_id, driver_id, expiration_date DESC);
CREATE INDEX idx_driver_pay_plans_company ON public.driver_pay_plans USING btree (company_id);
CREATE UNIQUE INDEX driver_payout_items_ref_uniq ON public.driver_payout_items USING btree (kind, ref_id);
CREATE INDEX idx_driver_payout_items_driver ON public.driver_payout_items USING btree (driver_id, kind);
CREATE INDEX idx_driver_payout_items_payout ON public.driver_payout_items USING btree (payout_id);
CREATE INDEX driver_payouts_driver_idx ON public.driver_payouts USING btree (driver_id, period_end DESC);
CREATE UNIQUE INDEX driver_payouts_live_period_uniq ON public.driver_payouts USING btree (driver_id, period_start, period_end) WHERE (voided_at IS NULL);
CREATE INDEX idx_driver_payouts_company_period ON public.driver_payouts USING btree (company_id, period_start, period_end);
CREATE INDEX driver_shifts_driver_idx ON public.driver_shifts USING btree (driver_id, clock_in_at DESC);
CREATE INDEX idx_driver_shifts_cleared_batch ON public.driver_shifts USING btree (cleared_batch_id);
CREATE INDEX idx_driver_shifts_open ON public.driver_shifts USING btree (driver_id, clock_in_at) WHERE (payout_id IS NULL);
CREATE INDEX idx_driver_shifts_payout ON public.driver_shifts USING btree (payout_id);
CREATE INDEX driver_trip_drafts_company_idx ON public.driver_trip_drafts USING btree (company_id, status, updated_at DESC);
CREATE INDEX driver_trip_drafts_driver_idx ON public.driver_trip_drafts USING btree (driver_id, status, updated_at DESC);
CREATE INDEX drivers_merged_into_idx ON public.drivers USING btree (merged_into) WHERE (merged_into IS NOT NULL);
CREATE INDEX idx_drivers_company ON public.drivers USING btree (company_id);
CREATE INDEX idx_fuel_driver ON public.fuel_logs USING btree (driver_id, log_date);
CREATE INDEX idx_gas_receipts_payout ON public.gas_receipts USING btree (payout_id);
CREATE INDEX manual_claim_records_company_idx ON public.manual_claim_records USING btree (company_id, service_date DESC);
CREATE INDEX manual_claim_records_driver_idx ON public.manual_claim_records USING btree (company_id, driver_id, service_date DESC);
CREATE INDEX medicaid_trip_legs_trip_idx ON public.medicaid_trip_legs USING btree (medicaid_trip_id);
CREATE INDEX idx_medicaid_trips_company ON public.medicaid_trips USING btree (company_id);
CREATE INDEX idx_medicaid_trips_dispatch_trip_id ON public.medicaid_trips USING btree (dispatch_trip_id);
CREATE INDEX medicaid_trips_created_by_idx ON public.medicaid_trips USING btree (created_by);
CREATE INDEX medicaid_trips_driver_idx ON public.medicaid_trips USING btree (driver_id, pickup_at DESC);
CREATE INDEX medicaid_trips_group_idx ON public.medicaid_trips USING btree (group_id);
CREATE INDEX medicaid_trips_rider_idx ON public.medicaid_trips USING btree (rider_id);
CREATE INDEX medicaid_trips_robot_worker_idx ON public.medicaid_trips USING btree (robot_worker_id) WHERE (robot_worker_id IS NOT NULL);
CREATE INDEX medicaid_trips_status_idx ON public.medicaid_trips USING btree (status, pickup_at DESC);
CREATE INDEX idx_messages_driver ON public.messages USING btree (driver_id, created_at DESC);
CREATE INDEX idx_passengers_company ON public.passengers USING btree (company_id);
CREATE UNIQUE INDEX passengers_company_medicaid_key ON public.passengers USING btree (company_id, medicaid_id) WHERE (medicaid_id IS NOT NULL);
CREATE UNIQUE INDEX passengers_device_id_key ON public.passengers USING btree (device_id);
CREATE INDEX payroll_audit_item_idx ON public.payroll_audit_log USING btree (payroll_item_id, created_at DESC);
CREATE INDEX payroll_items_driver_idx ON public.payroll_items USING btree (company_id, driver_id, service_date DESC);
CREATE INDEX payroll_items_status_idx ON public.payroll_items USING btree (company_id, payroll_status);
CREATE UNIQUE INDEX payroll_items_unique_claim ON public.payroll_items USING btree (company_id, ref_id) WHERE ((kind = 'claim'::text) AND (ref_id IS NOT NULL));
CREATE UNIQUE INDEX payroll_items_unique_manual_ref ON public.payroll_items USING btree (company_id, ref_id) WHERE ((kind = 'manual'::text) AND (ref_id IS NOT NULL));
CREATE INDEX idx_profiles_company ON public.profiles USING btree (company_id);
CREATE INDEX idx_ride_requests_company ON public.ride_requests USING btree (company_id);
CREATE INDEX ride_requests_status_offer_idx ON public.ride_requests USING btree (status, offer_expires_at);
CREATE INDEX idx_riders_company ON public.riders USING btree (company_id);
CREATE INDEX riders_medicaid_idx ON public.riders USING btree (medicaid_id);
CREATE INDEX riders_name_idx ON public.riders USING gin (to_tsvector('simple'::regconfig, full_name));
CREATE INDEX idx_robot_api_keys_active ON public.robot_api_keys USING btree (is_active) WHERE (is_active = true);
CREATE INDEX route_stops_route_seq_idx ON public.route_stops USING btree (route_id, sequence);
CREATE INDEX idx_routes_company ON public.routes USING btree (company_id);
CREATE INDEX idx_shifts_driver_date ON public.shifts USING btree (driver_id, shift_date);
CREATE INDEX sms_conversations_company_activity_idx ON public.sms_conversations USING btree (company_id, last_message_at DESC);
CREATE UNIQUE INDEX sms_conversations_company_contact_number_key ON public.sms_conversations USING btree (company_id, contact_phone, our_number);
CREATE INDEX sms_messages_company_idx ON public.sms_messages USING btree (company_id, created_at DESC);
CREATE INDEX sms_messages_conversation_idx ON public.sms_messages USING btree (conversation_id, created_at);
CREATE UNIQUE INDEX sms_messages_dedupe_key_key ON public.sms_messages USING btree (company_id, dedupe_key) WHERE (dedupe_key IS NOT NULL);
CREATE UNIQUE INDEX sms_messages_provider_message_id_key ON public.sms_messages USING btree (provider, provider_message_id) WHERE (provider_message_id IS NOT NULL);
CREATE UNIQUE INDEX staff_conversations_pair_idx ON public.staff_conversations USING btree (company_id, LEAST(member_a, member_b), GREATEST(member_a, member_b));
CREATE INDEX staff_messages_conversation_idx ON public.staff_messages USING btree (conversation_id, created_at);
CREATE UNIQUE INDEX state_portal_credentials_portal_company_uidx ON public.state_portal_credentials USING btree (portal_id, COALESCE(company_id, '00000000-0000-0000-0000-000000000000'::uuid));
CREATE INDEX subscription_payments_company_idx ON public.subscription_payments USING btree (company_id, paid_on DESC);
CREATE INDEX trip_destination_classifications_company_status_idx ON public.trip_destination_classifications USING btree (company_id, status);
CREATE UNIQUE INDEX trip_destination_classifications_trip_version_key ON public.trip_destination_classifications USING btree (trip_id, classifier_version);
CREATE INDEX trip_stops_trip_idx ON public.trip_stops USING btree (trip_id, sequence);
CREATE INDEX idx_trips_company ON public.trips USING btree (company_id);
CREATE INDEX idx_trips_driver ON public.trips USING btree (driver_id);
CREATE INDEX idx_trips_driver_completed ON public.trips USING btree (driver_id, scheduled_pickup_time) WHERE (payout_id IS NULL);
CREATE INDEX idx_trips_passenger ON public.trips USING btree (passenger_id);
CREATE INDEX idx_trips_payout ON public.trips USING btree (payout_id);
CREATE INDEX idx_trips_scheduled ON public.trips USING btree (scheduled_pickup_time);
CREATE INDEX idx_trips_status ON public.trips USING btree (status);
CREATE INDEX trips_round_trip_group_idx ON public.trips USING btree (round_trip_group_id);
CREATE INDEX idx_user_roles_company ON public.user_roles USING btree (company_id);
CREATE INDEX vehicle_expenses_category_idx ON public.vehicle_expenses USING btree (company_id, category, expense_date DESC);
CREATE INDEX vehicle_expenses_idx ON public.vehicle_expenses USING btree (company_id, driver_id, expense_date DESC);
