-- =====================================================================
-- RedArt - CURRENT SCHEMA EXPORT (generated, do not edit by hand)
-- Part 7: triggers on public tables
-- Source: live `public` schema, catalog introspection, read-only.
-- Contains no data, no secrets, no cron/net schedules.
-- Execute the parts strictly in filename order (01 -> 10).
-- =====================================================================

CREATE TRIGGER auto_pilot_runs_updated_at BEFORE UPDATE ON public.auto_pilot_runs FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER billing_rate_settings_stamp_company BEFORE INSERT ON public.billing_rate_settings FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER trg_billing_rate_settings_updated_at BEFORE UPDATE ON public.billing_rate_settings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER billing_records_stamp_company BEFORE INSERT ON public.billing_records FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER trg_billing_records_updated_at BEFORE UPDATE ON public.billing_records FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_protect_submitted_billing_records BEFORE UPDATE ON public.billing_records FOR EACH ROW EXECUTE FUNCTION protect_submitted_billing_records();
CREATE TRIGGER billing_settings_set_updated_at BEFORE UPDATE ON public.billing_settings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER chat_conversations_updated_at BEFORE UPDATE ON public.chat_conversations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER chat_messages_bump AFTER INSERT ON public.chat_messages FOR EACH ROW EXECUTE FUNCTION bump_chat_conversation();
CREATE TRIGGER claim_modifier_audit_stamp_company BEFORE INSERT ON public.claim_modifier_audit FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER claim_resubmissions_stamp_company BEFORE INSERT ON public.claim_resubmissions FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER claim_resubmissions_updated_at BEFORE UPDATE ON public.claim_resubmissions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER claim_service_lines_stamp_company BEFORE INSERT ON public.claim_service_lines FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER claim_service_lines_updated_at BEFORE UPDATE ON public.claim_service_lines FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER companies_set_updated_at BEFORE UPDATE ON public.companies FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_company_comm_settings_updated_at BEFORE UPDATE ON public.company_comm_settings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER company_pay_settings_updated_at BEFORE UPDATE ON public.company_pay_settings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER company_subscriptions_set_updated_at BEFORE UPDATE ON public.company_subscriptions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER destination_place_cache_stamp_company BEFORE INSERT ON public.destination_place_cache FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER destination_place_cache_updated_at BEFORE UPDATE ON public.destination_place_cache FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER destination_review_overrides_stamp_company BEFORE INSERT ON public.destination_review_overrides FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER stamp_dispatch_event_company_trg BEFORE INSERT ON public.dispatch_events FOR EACH ROW EXECUTE FUNCTION stamp_dispatch_event_company();
CREATE TRIGGER trg_dispatch_trip_report_drafts_updated_at BEFORE UPDATE ON public.dispatch_trip_report_drafts FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER driver_claim_payouts_set_updated_at BEFORE UPDATE ON public.driver_claim_payouts FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER driver_claim_payouts_stamp_company BEFORE INSERT ON public.driver_claim_payouts FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER driver_hour_clearings_stamp_company BEFORE INSERT ON public.driver_hour_clearings FOR EACH ROW EXECUTE FUNCTION stamp_company_from_driver();
CREATE TRIGGER trg_driver_hour_clearings_updated_at BEFORE UPDATE ON public.driver_hour_clearings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER driver_insurance_docs_stamp_company BEFORE INSERT ON public.driver_insurance_docs FOR EACH ROW EXECUTE FUNCTION stamp_company_from_driver();
CREATE TRIGGER driver_insurance_docs_updated_at BEFORE UPDATE ON public.driver_insurance_docs FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER driver_pay_set_updated_at BEFORE UPDATE ON public.driver_pay FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER driver_pay_stamp_company BEFORE INSERT ON public.driver_pay FOR EACH ROW EXECUTE FUNCTION stamp_company_from_driver();
CREATE TRIGGER driver_pay_plans_stamp_company BEFORE INSERT ON public.driver_pay_plans FOR EACH ROW EXECUTE FUNCTION stamp_company_from_driver();
CREATE TRIGGER driver_pay_plans_updated_at BEFORE UPDATE ON public.driver_pay_plans FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER driver_payouts_set_updated_at BEFORE UPDATE ON public.driver_payouts FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER driver_payouts_stamp_company BEFORE INSERT ON public.driver_payouts FOR EACH ROW EXECUTE FUNCTION stamp_company_from_driver();
CREATE TRIGGER driver_shifts_stamp_company BEFORE INSERT ON public.driver_shifts FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER driver_trip_drafts_stamp BEFORE INSERT OR UPDATE ON public.driver_trip_drafts FOR EACH ROW EXECUTE FUNCTION stamp_driver_trip_draft();
CREATE TRIGGER drivers_stamp_company BEFORE INSERT ON public.drivers FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER trg_drivers_updated BEFORE UPDATE ON public.drivers FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_notify_admin_driver_status AFTER UPDATE OF status ON public.drivers FOR EACH ROW EXECUTE FUNCTION notify_admin_driver_status();
CREATE TRIGGER events_set_updated_at BEFORE UPDATE ON public.events FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_fuel_updated BEFORE UPDATE ON public.fuel_logs FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER games_set_updated_at BEFORE UPDATE ON public.games FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER gas_receipts_stamp_company BEFORE INSERT ON public.gas_receipts FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER trg_incidents_updated BEFORE UPDATE ON public.incidents FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_inspections_updated BEFORE UPDATE ON public.inspections FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER manual_claim_records_stamp_company BEFORE INSERT ON public.manual_claim_records FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER manual_claim_records_updated_at BEFORE UPDATE ON public.manual_claim_records FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER medicaid_trip_legs_set_updated_at BEFORE UPDATE ON public.medicaid_trip_legs FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER medicaid_trips_stamp_company BEFORE INSERT ON public.medicaid_trips FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER stamp_medicaid_trip_creator BEFORE INSERT ON public.medicaid_trips FOR EACH ROW EXECUTE FUNCTION stamp_medicaid_trip_creator();
CREATE TRIGGER trg_ensure_billing_record AFTER INSERT OR UPDATE OF status ON public.medicaid_trips FOR EACH ROW EXECUTE FUNCTION ensure_billing_record();
CREATE TRIGGER trg_medicaid_trips_updated_at BEFORE UPDATE ON public.medicaid_trips FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_protect_submitted_claims BEFORE UPDATE ON public.medicaid_trips FOR EACH ROW EXECUTE FUNCTION protect_submitted_claims();
CREATE TRIGGER trg_news_items_updated BEFORE UPDATE ON public.news_items FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER passengers_stamp_company BEFORE INSERT ON public.passengers FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER trg_passengers_updated BEFORE UPDATE ON public.passengers FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER payroll_audit_stamp_company BEFORE INSERT ON public.payroll_audit_log FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER payroll_items_stamp_company BEFORE INSERT ON public.payroll_items FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER payroll_items_updated_at BEFORE UPDATE ON public.payroll_items FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_pricing_config_updated BEFORE UPDATE ON public.pricing_config FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_notify_admin_new_signup AFTER INSERT ON public.profiles FOR EACH ROW EXECUTE FUNCTION notify_admin_new_signup();
CREATE TRIGGER trg_profiles_updated BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER ride_requests_stamp_company BEFORE INSERT ON public.ride_requests FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER trg_ride_requests_updated BEFORE UPDATE ON public.ride_requests FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER riders_force_created_by BEFORE INSERT ON public.riders FOR EACH ROW EXECUTE FUNCTION riders_force_created_by();
CREATE TRIGGER riders_stamp_company BEFORE INSERT ON public.riders FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER trg_riders_updated_at BEFORE UPDATE ON public.riders FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER routes_set_updated_at BEFORE UPDATE ON public.routes FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER routes_stamp_company BEFORE INSERT ON public.routes FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER trg_saved_places_updated BEFORE UPDATE ON public.saved_places FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_shifts_updated BEFORE UPDATE ON public.shifts FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_sms_conversations_updated_at BEFORE UPDATE ON public.sms_conversations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_sms_messages_bump_conversation AFTER INSERT ON public.sms_messages FOR EACH ROW EXECUTE FUNCTION bump_sms_conversation();
CREATE TRIGGER trg_sms_messages_updated_at BEFORE UPDATE ON public.sms_messages FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER staff_conversations_set_updated_at BEFORE UPDATE ON public.staff_conversations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER staff_messages_bump AFTER INSERT ON public.staff_messages FOR EACH ROW EXECUTE FUNCTION bump_staff_conversation();
CREATE TRIGGER state_portal_credentials_stamp_company BEFORE INSERT ON public.state_portal_credentials FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER trg_portal_credentials_updated_at BEFORE UPDATE ON public.state_portal_credentials FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER submission_batches_stamp_company BEFORE INSERT ON public.submission_batches FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER submission_batches_updated_at BEFORE UPDATE ON public.submission_batches FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER subscription_payments_set_updated_at BEFORE UPDATE ON public.subscription_payments FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_billing_updated BEFORE UPDATE ON public.trip_billing_records FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trip_destination_classifications_stamp_company BEFORE INSERT ON public.trip_destination_classifications FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER trip_destination_classifications_updated_at BEFORE UPDATE ON public.trip_destination_classifications FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER guard_trip_driver_update BEFORE UPDATE ON public.trips FOR EACH ROW EXECUTE FUNCTION guard_trip_driver_update();
CREATE TRIGGER trg_release_driver_on_trip_end AFTER UPDATE OF status ON public.trips FOR EACH ROW EXECUTE FUNCTION release_driver_on_trip_end();
CREATE TRIGGER trg_trips_completed AFTER UPDATE OF status ON public.trips FOR EACH ROW EXECUTE FUNCTION increment_driver_trips();
CREATE TRIGGER trg_trips_rating_update AFTER UPDATE OF passenger_rating ON public.trips FOR EACH ROW EXECUTE FUNCTION update_driver_rating();
CREATE TRIGGER trg_trips_updated BEFORE UPDATE ON public.trips FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trips_stamp_company BEFORE INSERT ON public.trips FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER trips_sync_chat AFTER UPDATE ON public.trips FOR EACH ROW EXECUTE FUNCTION sync_trip_chat();
CREATE TRIGGER guard_user_roles_write BEFORE INSERT OR DELETE OR UPDATE ON public.user_roles FOR EACH ROW EXECUTE FUNCTION guard_user_roles_write();
CREATE TRIGGER trg_ensure_driver_row AFTER INSERT ON public.user_roles FOR EACH ROW EXECUTE FUNCTION ensure_driver_row();
CREATE TRIGGER user_roles_stamp_company BEFORE INSERT ON public.user_roles FOR EACH ROW EXECUTE FUNCTION stamp_company_id();
CREATE TRIGGER vehicle_expenses_stamp_company BEFORE INSERT ON public.vehicle_expenses FOR EACH ROW EXECUTE FUNCTION stamp_company_from_driver();
CREATE TRIGGER vehicle_expenses_updated_at BEFORE UPDATE ON public.vehicle_expenses FOR EACH ROW EXECUTE FUNCTION set_updated_at();
